### ISSUE TITLE
the setting words overlap

### ISSUE THREAD

**Issue by HackYardo** [aki65/aki65.github.io#1]
![670A8651B67E42E0351C5628B24D5B9E](https://user-images.githubusercontent.com/57677458/96956709-6d82d580-152b-11eb-9a7a-5367a91dd165.png)

Thanks for your work, that people can use LZ and KG on android devices!

**Comment by cryptpark** [comment]
I have the same thing, but only on the emulator. everything is fine on the tablet

**Comment by aki65** [comment]
The height of the dialog was a fixed percentage of screen height, so it was ok on big screens (like the one I tested on) but obviously not on smaller screens. In version 0.14 I gave the dialog a fixed size. I hope that's working for you, otherwise please tell me.
