### ISSUE TITLE
咨询落子分析里的两个数字的含义

### ISSUE THREAD

**Issue by allenlz** [aki65/aki65.github.io#100]
今天搜到了这个app，非常好用，很适合初学者学习。

不过落子分析里的数字一大一小，有一些困惑：
1）上面大一点的数字，应该是胜率。
2）下面小一点的数字，是什么含义呢？是目差么？

**Comment by aki65** [comment]
这是当前棋手的领先优势（点数）。因此，举例来说，如果轮到黑棋，-3 意味着人工智能预计黑棋（平均）最终会以 3 点的优势输掉对局。换句话说，黑棋稍稍落后。

**Comment by allenlz** [comment]
谢谢



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2023年9月3日(周日) 晚上9:34
收件人: ***@***.***&gt;;
抄送: ***@***.******@***.***&gt;;
主题: Re: [aki65/aki65.github.io] 咨询落子分析里的两个数字的含义 (Issue #100)




 
这是当前棋手的领先优势（点数）。因此，举例来说，如果轮到黑棋，-3 意味着人工智能预计黑棋（平均）最终会以 3 点的优势输掉对局。换句话说，黑棋稍稍落后。
