### ISSUE TITLE
Mainpage Suggestion: make it more clear?

### ISSUE THREAD

**Issue by HackYardo** [aki65/aki65.github.io#101]
I just sew people at Sensei Library (a nice Go wiki site better than wikipedia) not fine because he or she can not find a readme of BadukAI:

> Unfortunately, as of 2023-02-14, that page offers no documentation at all, let alone sufficient documentation to substantiate this claim. A little more may be gleaned from [ext] https://github.com/aki65/aki65.github.io/releases

- https://senseis.xmp.net/?Katago

I have never used a github page and a repo at the same time, how could it be more clear?

**Comment by aki65** [comment]
A direct link to the mainpage is just below the paragraph at Sensei Library, that you cited.

Moreover, the app now includes a "help" button in the settings menu, that leads to the mainpage.

So, everyone really should be able to find it. More serious is the fact, that the chinese version is outdated.

**Comment by HackYardo** [comment]
Does 1.19 version support android 12 and Dimensity 700? I can't download and install it for sixty hours...

在 2023-09-16 03:23:34，aki65 ***@***.***> 写道：


A direct link to the mainpage is just below the paragraph at Sensei Library, that you cited.

Moreover, the app now includes a "help" button in the settings menu, that leads to the mainpage.

So, everyone really should be able to find it. More serious is the fact, that the chinese version is outdated.

**Comment by aki65** [comment]
Android 12 is definitely supported. As for Dimensity 700, I don't know. But at least the 10b network, which runs on CPU, should work.

**Comment by HackYardo** [comment]
I will transl 1.19 index.html and translation.json in three days.

在 2023-09-20 03:30:34，aki65 ***@***.***> 写道：


Android 12 is definitely supported. As for Dimensity 700, I don't know. But at least the 10b network, which runs on CPU, should work.

**Comment by HackYardo** [comment]
Uh, the english version and chniese version is not line-to-line, it's a horrible  disaster! And there're many unnessary "entry"s that make the text longer. Could I delete these entrys?

在 2023-09-20 03:30:34，aki65 ***@***.***> 写道：


Android 12 is definitely supported. As for Dimensity 700, I don't know. But at least the 10b network, which runs on CPU, should work.

**Comment by aki65** [comment]
As long as the resulting display in the browser does not change, you can re-format as you like.

**Comment by HackYardo** [comment]
I have to say the **pan, zoom, rotate** feature is very nice. Besides that, I have a question about "branches(moves) to show in analyze", could BadukAI add a feature "branches to analyze" via KataGo GTP command `analyze maxmoves n`?

**Comment by HackYardo** [comment]
I have tried `maxmoves` command flag but it seems only a "vertices to display" not "vertices to consider", it can not speed up computing by considering less vertices. So I close the issue.
