### ISSUE TITLE
Network Suggestion: Sync to Gitee

### ISSUE THREAD

**Issue by HackYardo** [aki65/aki65.github.io#102]
May I sync the whole project to Gitee.com, a Chinese Github, to get a much faster and more stable network link? I have download the newest version for seventy hours and install once but no luck to let it run.

**Comment by aki65** [comment]
Feel free to do so. But if it took 70 hours to get one apk, copying the whole project will take a while ...

**Comment by HackYardo** [comment]
It doesn't support releases, which are binary and not text, so they are not Git compatible... :( ...but I finally download and install 1.19 version successfully via Aria2, a CLI download tool.

在 2023-09-20 03:27:00，aki65 ***@***.***> 写道：


Feel free to do so. But if it took 70 hours to get one apk, copying the whole project will take a while ...
