### ISSUE TITLE
bug in Ko play

### ISSUE THREAD

**Issue by bltoby** [aki65/aki65.github.io#104]
With the latest release when it cames to ko play, sometimes the software will suggest you to capture back opponent's stone immediately without finding a ko threat.

This bug should be fixed. Thanks.

**Comment by aki65** [comment]
I couldn't reproduce that. Could you please post a position where that happens ?

**Comment by bltoby** [comment]
I can't reproduce the bug for sure either. Even with the same sgf or at the same position, when I restart BadukAI, the bug can disappear by itself. 

But I noticed this bug will mostly come up (with about 20 percent possibility) when during longer analysing.

**Comment by aki65** [comment]
Nevertheless, if you encounter the problem the next time, please post a screenshot with the wrong suggested move and save the sgf and post it. Even a position, where it **may** happen, would possibly help.

**Comment by bltoby** [comment]
Some follow up Info

The last release without this bug is 1.18.12

With any sgf, that includes ko plays, can this bug be reproduced at the chance of about 50%. 

But under the following condition:
The ko plays should occur relatively late, because only that can assure BadukAI has  been analyzing the sgf for a longer time.

Can't upload attachment with Smartphone, Just copied the kifu in txt form.
Ko play from move 244 to 274.  Remember to analyze the whole game from the beginning for at least 2000v per move. The bug will come and go, meaning when it occurred, move backwards and then forward, it will disappear by itself.

(
;B[pd]TL[0,0];W[dp]TL[0,0];B[pq]TL[0,0];W[dc]TL[0,0]
;B[ce]TL[0,0];W[ed]TL[0,0];B[ch]TL[0,0];W[qo]TL[0,0]
;B[qm]TL[0,0];W[op]TL[0,0];B[mq]TL[0,0];W[oq]TL[0,0]
;B[or]TL[0,0];W[nr]TL[0,0];B[pr]TL[0,0];W[nq]TL[0,0]
;B[pp]TL[0,0];W[po]TL[0,0];B[oo]TL[0,0];W[no]TL[0,0]
;B[on]TL[0,0];W[rq]TL[0,0];B[mr]TL[0,0];W[os]TL[0,0]
;B[mp]TL[0,0];W[np]TL[0,0];B[mm]TL[0,0];W[ms]TL[0,0]
;B[kr]TL[0,0];W[mo]TL[0,0];B[ls]TL[0,0];W[lo]TL[0,0]
;B[ns]TL[0,0];W[pm]TL[0,0];B[pn]TL[0,0];W[ms]TL[0,0]
;B[qp]TL[0,0];W[ro]TL[0,0];B[ns]TL[0,0];W[qn]TL[0,0]
;B[om]TL[0,0];W[rm]TL[0,0];B[pl]TL[0,0];W[ms]TL[0,0]
;B[rp]TL[0,0];W[sp]TL[0,0];B[ns]TL[0,0];W[ql]TL[0,0]
;B[ps]TL[0,0];W[pk]TL[0,0];B[kn]TL[0,0];W[ko]TL[0,0]
;B[jo]TL[0,0];W[jp]TL[0,0];B[io]TL[0,0];W[kq]TL[0,0]
;B[ip]TL[0,0];W[iq]TL[0,0];B[jr]TL[0,0];W[jq]TL[0,0]
;B[hq]TL[0,0];W[ln]TL[0,0];B[lm]TL[0,0];W[ir]TL[0,0]
;B[hr]TL[0,0];W[hs]TL[0,0];B[js]TL[0,0];W[gr]TL[0,0]
;B[gq]TL[0,0];W[fq]TL[0,0];B[fr]TL[0,0];W[hp]TL[0,0]
;B[gs]TL[0,0];W[gp]TL[0,0];B[is]TL[0,0];W[km]TL[0,0]
;B[jn]TL[0,0];W[jm]TL[0,0];B[kp]TL[0,0];W[ol]TL[0,0]
;B[mn]TL[0,0];W[pm]TL[0,0];B[qf]TL[0,0];W[ll]TL[0,0]
;B[lp]TL[0,0];W[cj]TL[0,0];B[cp]TL[0,0];W[co]TL[0,0]
;B[cq]TL[0,0];W[dq]TL[0,0];B[dr]TL[0,0];W[er]TL[0,0]
;B[es]TL[0,0];W[cr]TL[0,0];B[eq]TL[0,0];W[bq]TL[0,0]
;B[ep]TL[0,0];W[bp]TL[0,0];B[jd]TL[0,0];W[df]TL[0,0]
;B[cf]TL[0,0];W[dh]TL[0,0];B[ci]TL[0,0];W[di]TL[0,0]
;B[bj]TL[0,0];W[bk]TL[0,0];B[dg]TL[0,0];W[eg]TL[0,0]
;B[cg]TL[0,0];W[dj]TL[0,0];B[cc]TL[0,0];W[cb]TL[0,0]
;B[dd]TL[0,0];W[de]TL[0,0];B[cd]TL[0,0];W[db]TL[0,0]
;B[md]TL[0,0];W[qc]TL[0,0];B[pc]TL[0,0];W[qd]TL[0,0]
;B[qe]TL[0,0];W[pb]TL[0,0];B[ob]TL[0,0];W[rb]TL[0,0]
;B[pa]TL[0,0];W[qa]TL[0,0];B[qb]TL[0,0];W[bc]TL[0,0]
;B[bd]TL[0,0];W[pb]TL[0,0];B[nc]TL[0,0];W[oa]TL[0,0]
;B[na]TL[0,0];W[hc]TL[0,0];B[pa]TL[0,0];W[rd]TL[0,0]
;B[qb]TL[0,0];W[ra]TL[0,0];B[ic]TL[0,0];W[hd]TL[0,0]
;B[jf]TL[0,0];W[in]TL[0,0];B[nn]TL[0,0];W[en]TL[0,0]
;B[fn]TL[0,0];W[fm]TL[0,0];B[gm]TL[0,0];W[gn]TL[0,0]
;B[hn]TL[0,0];W[fo]TL[0,0];B[im]TL[0,0];W[gl]TL[0,0]
;B[ik]TL[0,0];W[hj]TL[0,0];B[hk]TL[0,0];W[gk]TL[0,0]
;B[ij]TL[0,0];W[qh]TL[0,0];B[pi]TL[0,0];W[qi]TL[0,0]
;B[hi]TL[0,0];W[bb]TL[0,0];B[bi]TL[0,0];W[gj]TL[0,0]
;B[nk]TL[0,0];W[nj]TL[0,0];B[oj]TL[0,0];W[nl]TL[0,0]
;B[ml]TL[0,0];W[mk]TL[0,0];B[lk]TL[0,0];W[mj]TL[0,0]
;B[lj]TL[0,0];W[mh]TL[0,0];B[ph]TL[0,0];W[pg]TL[0,0]
;B[og]TL[0,0];W[qg]TL[0,0];B[of]TL[0,0];W[li]TL[0,0]
;B[ni]TL[0,0];W[ok]TL[0,0];B[mi]TL[0,0];W[nk]TL[0,0]
;B[nh]TL[0,0];W[pj]TL[0,0];B[hg]TL[0,0];W[gh]TL[0,0]
;B[hh]TL[0,0];W[rs]TL[0,0];B[re]TL[0,0];W[sd]TL[0,0]
;B[se]TL[0,0];W[pb]TL[0,0];B[sh]TL[0,0];W[rg]TL[0,0]
;B[sg]TL[0,0];W[pf]TL[0,0];B[pe]TL[0,0];W[oe]TL[0,0]
;B[ne]TL[0,0];W[oh]TL[0,0];B[ng]TL[0,0];W[oi]TL[0,0]
;B[sk]TL[0,0];W[rk]TL[0,0];B[sl]TL[0,0];W[sm]TL[0,0]
;B[sj]TL[0,0];W[rj]TL[0,0];B[fg]TL[0,0];W[ff]TL[0,0]
;B[eh]TL[0,0];W[ef]TL[0,0];B[fh]TL[0,0];W[gi]TL[0,0]
;B[gg]TL[0,0];W[aj]TL[0,0];B[ai]TL[0,0];W[ad]TL[0,0]
;B[ae]TL[0,0];W[ac]TL[0,0];B[bf]TL[0,0];W[ak]TL[0,0]
;B[gf]TL[0,0];W[ge]TL[0,0];B[hb]TL[0,0];W[gb]TL[0,0]
;B[ib]TL[0,0];W[ie]TL[0,0];B[je]TL[0,0];W[if]TL[0,0]
;B[ig]TL[0,0];W[he]TL[0,0];B[ga]TL[0,0];W[fb]TL[0,0]
;B[fp]TL[0,0];W[hm]TL[0,0];B[il]TL[0,0];W[go]TL[0,0]
;B[ej]TL[0,0];W[ek]TL[0,0];B[ei]TL[0,0];W[dk]TL[0,0]
;B[qb]TL[0,0];W[ag]TL[0,0];B[af]TL[0,0];W[pb]TL[0,0]
;B[qr]TL[0,0];W[oa]TL[0,0];B[rr]TL[0,0];W[od]TL[0,0]
;B[oc]TL[0,0];W[sr]TL[0,0];B[pa]TL[0,0];W[nf]TL[0,0]
;B[mf]TL[0,0];W[oa]TL[0,0];B[qq]TL[0,0];W[sq]TL[0,0]
;B[pa]TL[0,0];W[mg]TL[0,0];B[nd]TL[0,0];W[oa]TL[0,0]
;B[so]TL[0,0];W[sn]TL[0,0];B[pa]TL[0,0];W[oe]TL[0,0]
;B[od]TL[0,0];W[oa]TL[0,0];B[fa]TL[0,0];W[ea]TL[0,0]
;B[ha]TL[0,0];W[pa]TL[0,0];B[qs]TL[0,0];W[id]TL[0,0]
;B[ss]TL[0,0];W[jc]TL[0,0];B[jb]TL[0,0];W[rs]TL[0,0]
;B[kc]TL[0,0];W[so]TL[0,0];B[ss]TL[0,0];W[nb]TL[0,0]
;B[mb]TL[0,0];W[rs]TL[0,0];B[fj]TL[0,0];W[cs]TL[0,0]
;B[fk]TL[0,0];W[fl]TL[0,0];B[eo]TL[0,0];W[do]TL[0,0]
;B[ds]TL[0,0];W[ho]TL[0,0];B[in]TL[0,0];W[hl]TL[0,0]
;B[ss]TL[0,0];W[ri]TL[0,0];B[si]TL[0,0];W[rs]TL[0,0]
;B[cl]TL[0,0];W[ck]TL[0,0];B[ss]TL[0,0];W[tt]TL[0,0]
;B[hf]TL[0,0];W[fe]TL[0,0];B[rs]TL[0,0];W[tt]TL[0,0]
;B[fi]TL[0,0];W[nm]TL[0,0];B[rf]TL[0,0];W[rl]TL[0,0]
;B[sf]TL[0,0];W[rh]TL[0,0];B[tt]TL[0,0];W[jg]TL[0,0]
;B[jh]TL[0,0];W[kg]TL[0,0];B[ii]TL[0,0];W[tt]TL[0,0]
;B[tt]TL[0,0]
)

**Comment by aki65** [comment]
Thank you very much for all the additional information. I did the following:
load 18b network s740...
load your kifu
set visits/move to 2000
tap "analyse all" and let it run until the end of the game.

Although I repeated this test 8 times, the bug never occured. What are you doing differently ?

**Comment by bltoby** [comment]
[bug.sgf.txt](https://github.com/aki65/aki65.github.io/files/13444842/bug.sgf.txt)

finally I could reproduce the bug with the uploaded sgf file. (remember to delete the.txt)

Load the sgf to BadukAI, press 'ponder', AI will suggest black to play at f12, then play at f12. Now AI will suggest white to play at f13 to capture back directly. That's the bug.

Repeat the process, if you didn't reproduce the bug at the first try.

**Comment by aki65** [comment]
Thank you very much for reproducing the issue. I fixed it in https://github.com/aki65/aki65.github.io/releases/tag/v1.19.4 (at least it doesn't occur anymore on my device).
