### ISSUE TITLE
Could the app autosave the current game when be killed?

### ISSUE THREAD

**Issue by Jhering** [aki65/aki65.github.io#109]
When BadukAI app was killed by system, eg. battery manager, the current game losed at all.

Could you please add a featrue which can autosave the current game. When we reopen the app, it can restore the previous game automatically.

**Comment by aki65** [comment]
Autosave already exists. After reopening the app, tap "load sgf", then "load last game" (to retrieve the full sequence of moves) or "load last position" (to retrieve the last board position).

**Comment by Jhering** [comment]
Oh, I saw the featrue 'load sgf', it's amazing. Thank you for a lot.

**Comment by foxrainowo** [comment]
是的，這些功能可以恢復棋盤狀態，但是之前訪問的結果都沒有了。可不可以新增自動保存訪問結果的功能？

**Comment by Jhering** [comment]
It's awesome. 
Thank you for your hard work.
