### ISSUE TITLE
Where are the latest models from distributed training?

### ISSUE THREAD

**Issue by HackYardo** [aki65/aki65.github.io#11]
Is the distributed training of KataGo begin? Where are they?
 How many blocks do they have, 50b or 60b? Are they stronger than g170-b40c256x2-s5095420928-d1229425124 and have more ELO than 1919?

**Comment by cryptsport** [comment]
https://lifein19x19.com/viewtopic.php?p=262468#p262468

**Comment by HackYardo** [comment]
@cryptsport Thank you very much!
