### ISSUE TITLE
經過量化的權重比原來的權重弱

### ISSUE THREAD

**Issue by foxrainowo** [aki65/aki65.github.io#116]
我使用手機版的權重和電腦版的權重進行對局，在同一局面下，相同計算量下，手機版明顯比電腦版弱。

有沒有方法改善呢？

**Comment by aki65** [comment]
在 Playouts 数量相同的情况下，我在 BadukAI 权重和原始权重之间进行了数百场比赛。而 BadukAI 的权重要弱 30 ELO（由于采用了 8 位量化）。这只是很小的差别。
从统计学角度来看，一场比赛并不能说明什么。

**Comment by HackYardo** [comment]
The same issue I find recently? With the same playouts and the same model, Phone Android BadukAI maybe a little weaker than Laptop Linux Sabaki and would lose more games. Is that ture? Or some issue just caused by statistics？
