### ISSUE TITLE
change the rules

### ISSUE THREAD

**Issue by Fly143** [aki65/aki65.github.io#119]
It is hoped that the settings will include an option to switch between go rules, such as the common Chinese rules, Japanese rules, and Korean rules. Instead of only being able to use a specific rule of the software.Because in some situations, with specific game records, the result of victory or defeat can be completely different under different rules.

**Comment by aki65** [comment]
In the latest release https://github.com/aki65/aki65.github.io/releases/tag/v1.19.8 you can change the rules in the settings and BadukAI will send them to KataGo. Be aware though, that there are minor differences between KataGo's rule implementation and the human rules (see https://lightvector.github.io/KataGo/rules.html and the documentation of kata-set-rules in https://github.com/lightvector/KataGo/blob/master/docs/GTP_Extensions.md)

**Comment by Fly143** [comment]
This is just so cool！

**Comment by Fly143** [comment]
Perhaps the translation of "Chinese" can be further optimized. 
中文＝中国规则
日本的＝日本规则
韩国的＝韩国规则

**Comment by Fly143** [comment]
Because I am a Chinese, I think the translation of the rules related to Chinese can be further optimized. 
中文＝中国规则
日本的＝日本规则
韩国的＝韩国规则
@aki65

**Comment by aki65** [comment]
Thanks for the translations. I integrated them in the latest version ( https://github.com/aki65/aki65.github.io/releases/tag/v1.19.9 ).

**Comment by VK3002** [comment]
Hi aki65,
Could you please add an option for advanced user to customise the rules? Katago does support this feature.
It's fun to see katago behaves in different style / have different playing favours, also, I think it useful to learn how to handle the same situation under different specific rules(especially the `ScoringRule`, `TaxRule` and `WhiteHandicapBonus`) from katago.
Just provide an input box to change specific rules(e.g. we can type something like `kata-set-rule ko SIMPLE`, `kata-set-rule hasButton false `, `kata-set-rule tax ALL`, `kata-set-rule whiteHandicapBonus N-1` ...in it). Or you can do it your own way.
Thanks

**Comment by aki65** [comment]
Typing GTP commands is quite inconvenient and spelling errors may cause trouble, so I made a UI for setting the rules features (allowing custom combinations): https://github.com/aki65/aki65.github.io/releases/tag/v1.19.23

**Comment by Fly143** [comment]
@aki65 Suggestions on Chinese translation：

【设置董事会外观】→【设置主题外观】

Regarding the modification of the UI part of the rules:：

【习俗】→【自定义】

ko：

【SIMPLE】→【不禁全同】

【POSITIONAL】→【严格禁全同】

【SITUATIONAL】→【同一方落子后禁全同】

scoring：

【AREA】→【数子法】

【TERRITORY】→【数目法】

tax：

【tax】→【还棋头】

【NONE】→【不还棋头】

【SEKI】→【仅双活棋块还棋头】

【ALL】→【所有棋块均还棋头】

whiteHandicapBonus：

【whiteHandicapBonus】

→【让子贴还】

【0】→【不贴还】

【N-1】→【让N子还N-1目】

【N-】→【让N子还N目】

suicide：

【suicide】→【多颗棋子的棋块自杀】

hasButton：

【hasButton】→【手指规则下稍后方贴还0.5目】

friendlyPassOk：

【friendlyPassOk】→【终局时不清除盘面死子】

**Comment by Fly143** [comment]
> @aki65中文翻译建议：
> 
> 【设置董事会外观】→【设置主题外观】
> 
> 关于规则UI部分修改：
> 
> 【习俗】→【国家】
> 
> 柯：
> 
> 【简单】→【不禁全部】
> 
> 【政策】→【严格禁止全部】
> 
> 【情境】→【同一方落子后全同】
> 
> 评分：
> 
> 【区域】→【数子法】
> 
> 【疆土】→【数目法】
> 
> 税：
> 
> 【税】→【还棋头】
> 
> 【NONE】→【不还棋头】
> 
> 【SEKI】→【仅双活棋块还棋头】
> 
> 【ALL】→【所有棋牌均还棋头】
> 
> 白色让分奖金：
> 
> 【白让分红利】
> 
> →【讓子贴还】
> 
> 【0】→【不贴】
> 
> 【N-1】→【让N子还N-1目】
> 
> 【N-】→【让N子还N目】
> 
> 自杀：
> 
> 【自杀】→【多颗棋子棋块自杀】
> 
> 有按钮：
> 
> 【hasButton】→【手指规则下下方贴还0.5目】
> 
> friendlyPassOk：
> 
> 【friendlyPassOk】→【终局时不清除盘面死子】

Correction：
【hasButton】→【让字规则下收后方贴还0.5目】

**Comment by Fly143** [comment]
> @aki65用法建议：
> 
> 【设置董事会外观】→【设置主题外观】
> 
> 关于规则UI部分修改：
> 
> 【警編】→【國家】
> 
> 柯：
> 
> 【简单】→【不禁全部】
> 
> 【政策】→【严格禁止全部】
> 
> 【情境】→【同一方落子后全同】
> 
> 评分：
> 
> 【区域】→【数据法】
> 
> 【疆土】→【数目法】
> 
> 稅：
> 
> 【税】→【还棋头】
> 
> 【NONE】→【不还棋头】
> 
> 【SEKI】→【仅双活棋块还棋头】
> 
> 【全部】→【所有棋牌均还棋头】
> 
> 白色授予奖金：
> 
> 【白讓分紅利】
> 
> →【讓子贴还】
> 
> 【0】→【不贴】
> 
> 【N-1】→【让N子还N-1目】
> 
> 【N-】→【让N子还N目】
> 
> 自杀：
> 
> 【自杀】→【多颗棋子棋块自杀】
> 
> 有按钮：
> 
> 【hasButton】→【手指规则下方贴还0.5目】
> 
> friendlyPassOk：
> 
> 【friendlyPassOk】→【终局时不清除盘面死子】

Correction：
【hasButton】→【让子规则下收后方贴还0.5目】

**Comment by Fly143** [comment]
@aki65 Suggestions on Chinese translation：

【设置董事会外观】→【设置主题外观】

Regarding the modification of the UI part of the rules:：

【习俗】→【自定义】

ko：

【SIMPLE】→【不禁全同】

【POSITIONAL】→【严格禁全同】

【SITUATIONAL】→【同一方落子后禁全同】

scoring：

【AREA】→【数子法】

【TERRITORY】→【数目法】

tax：

【tax】→【还棋头】

【NONE】→【不还棋头】

【SEKI】→【仅双活棋块还棋头】

【ALL】→【所有棋块均还棋头】

whiteHandicapBonus：

【whiteHandicapBonus】

→【让子贴还】

【0】→【不贴还】

【N-1】→【让N子还N-1目】

【N-】→【让N子还N目】

suicide：

【suicide】→【多颗棋子的棋块自杀】

hasButton：

【hasButton】→【让子规则下收后方贴还0.5目】

friendlyPassOk：

【friendlyPassOk】→【终局时不清除盘面死子】

**Comment by VK3002** [comment]
Great! Thanks you, @aki65 .
感謝閣下提供中文翻譯 @Fly143 :+1:

**Comment by aki65** [comment]
I had high hopes that I could at least translate '0' correctly, but it was not to be ... just kidding ... thank you very much for the translations. I integrated them here: https://github.com/aki65/aki65.github.io/releases/tag/v1.19.24

**Comment by Fly143** [comment]
> 非常感谢你的翻译。我把它们整合在这里：https://github.com/aki65/aki65.github.io/releases/tag/v1.19.24

@aki65 I'm very sorry! Due to my negligence, there is a mistake in the Chinese translation. 【hasButton】should be translated as 【数子规则下收后方贴还0.5目】

**Comment by Fly143** [comment]
> Thank you very much for the translations. I integrated them here: https://github.com/aki65/aki65.github.io/releases/tag/v1.19.24

@aki65 I'm very sorry! Due to my negligence, there is a mistake in the Chinese translation. 【hasButton】should be translated as 【数子规则下收后方贴还0.5目】

**Comment by aki65** [comment]
No problem. I changed it: https://github.com/aki65/aki65.github.io/releases/tag/v1.19.25
