### ISSUE TITLE
Addthenumber ofmovesdisplayforthepieceson theboard

### ISSUE THREAD

**Issue by Fly143** [aki65/aki65.github.io#120]
Add the number of moves display for the pieces on the board.
When opening the sgf game record with annotations, whether it is possible to add the number of moves display for the pieces on the board, because some annotations indicate the role of which move, without the display of the number of moves, I don't know which piece on the board the annotation is referring to.
![IMG_20240207_215502](https://github.com/aki65/aki65.github.io/assets/80356009/0d3de045-6ff1-439e-aeb6-5e63a90dd2b2)

**Comment by aki65** [comment]
Tick "#" in settings in the line starting with "board:", then you get numbered stones.
