### ISSUE TITLE
可否用动画显示分析的每一个结果

### ISSUE THREAD

**Issue by chengshouzhong** [aki65/aki65.github.io#121]
棋局分析后显示的坐标结果里，用手指头按住的时候，显示的结果不是动画的，看着有些迷惑，比如遇到打劫的时候显示的棋子顺序有时候看不清楚。我的意思是如果能加入动画播放每一个结果，看起来会更舒适一些，不知技术层面上能否实现呢？谢谢！

**Comment by aki65** [comment]
在最新版本（ https://github.com/aki65/aki65.github.io/releases/tag/v1.19.9 ）中，序列是动画的。您可以在设置（ "管理时间设置" -> "变体的动画速度 （秒/手)" ）中调整动画的速度。

**Comment by chengshouzhong** [comment]
> 在最新版本（ https://github.com/aki65/aki65.github.io/releases/tag/v1.19.9 ）中，序列是动画的。您可以在设置（ "管理时间设置" -> "变体的动画速度 （秒/手)" ）中调整动画的速度。

谢谢您，新年快乐！
