### ISSUE TITLE
Detect stones in image freeze on XiaoMI HyperOS

### ISSUE THREAD

**Issue by smilefox76** [aki65/aki65.github.io#123]
Hello aki65, 
   I have a problem with using baduk_ai at the latest Xiaomi phone system(Xiaomi HyperOS).
   When I use the "Detect stones in image" function , baduk_ai freeze at "Image is being analysed. Please wait ..." screen.
   This function works very well before I updated system OS.
    I do not have  more information now.
   But if you have plans to look into this issue, I will do my best to provide further information。
  Thanks a lot.

**Comment by aki65** [comment]
Hi smilefox76,

by coincidence I received HyperOS for my Xiaomi phone today and ... stone detection freezes. So I could analyze it myself. The fix is here: https://github.com/aki65/aki65.github.io/releases/tag/v1.19.10
