### ISSUE TITLE
能否优化一下一部分手机的应用分身功能创建的BadukAI没有读取权限

### ISSUE THREAD

**Issue by chaoclc** [aki65/aki65.github.io#125]
想用手机的应用分身功能创建多个BadukAI，跨屏到电脑显示屏上，进行同一个手机设备对抗测试b18权重与b28权重性能 。

其中moto手机创建的BadukAI分身，没有读取存储的棋谱权限也无法添加优化的神经网络权限，只能使用内置的权重。
而另一部手机realme使用的是oppo的系统却可以有读取权限使用正常，只是它的跨屏互联功能不满意很少使用。

moto手机的分身功能与跨屏连接电脑的功能都很优秀，平时都使用moto手机。如果不能解决这个问题，请下次更新时提供一个内置b18权重的应用程序下载，谢谢。

**Comment by aki65** [comment]
我不想在标准版本的应用程序中加入 18b 网络，因为该网络只能在最近的中端和高端 Snapdragon 芯片组上运行。在所有其他设备上，它都会崩溃，这不是用户所期望的内置网络。

不过，为了方便大家使用，我特意发布了一个版本（ https://github.com/aki65/aki65.github.io/releases/tag/v1.19.17 ）。它包括 18b 网络，而不是 20b 网络。我希望在操作系统问题解决之前，这可以作为一种变通办法。

**Comment by chaoclc** [comment]
好的，谢谢

获取Outlook for Android<https://aka.ms/AAb9ysg>
________________________________

**Comment by bltoby** [comment]
Would like to know if the new officially published 28B network stronger than best 18B network on the same device with same thinking time for example 5 secs or 10 secs.

**Comment by chaoclc** [comment]
现在同一手机5秒和10秒短时间测试是b18权重网络胜。猜测再经过一段时间训练b28会提升很快。

获取Outlook for Android<https://aka.ms/AAb9ysg>
________________________________

**Comment by aki65** [comment]
I uploaded an optimized version of the latest 28b network (first one published on katagotraining.org) here: https://github.com/aki65/aki65.github.io/releases/tag/v1.19.18
On my device it seems stronger than the latest 18b network at equal time (but haven't done enough matches to be statistically significant).

**Comment by chaoclc** [comment]
测试了几盘，时间长一点，10秒或者10秒以上b28胜

获取Outlook for Android<https://aka.ms/AAb9ysg>
________________________________

**Comment by chaoclc** [comment]
最新优化的b28权重很强大，测试了几盘，同一手机设备极短时间3秒也能够胜b18权重。
