### ISSUE TITLE
Is it possible to use original katago network

### ISSUE THREAD

**Issue by bltoby** [aki65/aki65.github.io#126]
Hello, is it possible to make badukai be capable to use original katago network. How is the performance drawdown?

**Comment by aki65** [comment]
BadukAI can already do this (just select the original .bin.gz and no .dlc/.tflite file, then tap "load"). However, there is a size limit on the model files (2**28 bytes), which is exceeded by the 28b models, so these can't be loaded with versions <= 19.19.

I fixed this in https://github.com/aki65/aki65.github.io/releases/tag/v1.19.20 , so with this version you can also load the original 28b models. For best performance in this case use 8 threads. However, the speed dropdown is still huge (factor 70 on my device) ...

**Comment by bltoby** [comment]
Just tried original networks, the slowdown is really Intolerable though.
