### ISSUE TITLE
  Buggy auto-repeat function with buttons < and >

### ISSUE THREAD

**Issue by bltoby** [aki65/aki65.github.io#127]
The bug can be triggered by keep long pressing > ( for example) and then swipe away from the button > . The auto repeat can't be stopped anymore.
 
This bug occured accidentally quite a few times, even if I didn't intend to use the auto repeat function.

p.s. 
Could you please update the strongest 28b network if you have time for that. Thanks

**Comment by aki65** [comment]
In the UI framework, that I use, the default behaviour of buttons in the scenario described is a little strange. Luckily, there is a flag to fix that, so the bug should be gone in the latest release: https://github.com/aki65/aki65.github.io/releases/tag/v1.19.21

**Comment by aki65** [comment]
The currently strongest weights are here: https://github.com/aki65/aki65.github.io/releases/tag/v1.19.22
