### ISSUE TITLE
Analysis of other branches of game tree 

### ISSUE THREAD

**Issue by bltoby** [aki65/aki65.github.io#128]
The analysis of other branches than main var can't be saved.

The file size of sgf becomes much bigger after saving the analysis, is it possible to optimize it to keep the file size more compact?

**Comment by aki65** [comment]
I fixed the bug concerning analysis of branches.

I optimized the size of the saved analysis, but I can't change the fact, that it's a lot of data. In my tests I now get around 1 MB for a full analysis of a game with 250 moves. Considering that a simple photo takes 2-3 MB these days, that should be manageable.

**Comment by bltoby** [comment]
I tried the new release, the bug is get fixed and the optimization is good enough, it reduced the file size of analysis by a lot.

Amazing and Thanks👍

**Comment by bltoby** [comment]
Does the full analysis save calculations of 100 suggested moves? If I set "moves to show" in the app to 10, which I think is by far enough, will the analysis be also limited to 10 suggestions plus the actually played move (if the played move is not between the 10 suggestions)?

**Comment by aki65** [comment]
No, "moves to show" only limits the number of dots displayed on the board (to prevent visual information overflow). The number of moves to be analyzed is determined by KataGo's search engine (and depends a lot on the board position).
