### ISSUE TITLE
Can you add a lz weight of 20b?

### ISSUE THREAD

**Issue by uestccokey** [aki65/aki65.github.io#13]
I think it might be stronger than the current 15b

**Comment by aki65** [comment]
The 15b network I use is one of those late 15b networks that were trained against 40b selfplay. It is only slightly weaker than the strongest 20b network at equal playouts, so I would not expect any significant advantage for 20b at equal time.
And if you need a stronger network, there is still the built-in 40b one.

**Comment by uestccokey** [comment]
OK, is the built-in 40B weight the latest 284 of LZ?

**Comment by aki65** [comment]
No, it's 273 which was the latest network when I started working on BadukAI. I never updated it since people were mainly interested in KataGo. But when I find the time I will optimize the current LZ network and include it in BadukAI.
