### ISSUE TITLE
A bug that causes the app to freeze.

### ISSUE THREAD

**Issue by Fly143** [aki65/aki65.github.io#132]
https://github.com/user-attachments/assets/b9fb2bfe-0fa0-4ee5-8bfc-d8fcd8b45fff

I can't enable the time setting. It will cause the app to freeze.

The version of the APP is the 1.20.6. The mobile phone model is Xiaomi 13 Pro. The system is HyperOS.

**Comment by Fly143** [comment]
I have tried restarting the app and rebooting the phone, but this did not solve the problem.

**Comment by Fly143** [comment]
When I use version 1.20.4, it is normal.

**Comment by aki65** [comment]
Sorry, I did some self-atari when producing 1.20.6. Thank you very much for reporting. I fixed it here: https://github.com/aki65/aki65.github.io/releases/tag/v1.20.7
