### ISSUE TITLE
Does KataGo can't resign under control when in kyu-rank mode?

### ISSUE THREAD

**Issue by HackYardo** [aki65/aki65.github.io#16]
I set resign-score=30 and resign-winrate=-0.80, then I play kyu-rank mode from 30 to 1, it seems that KataGoes resign later than the board positions, which are over 30 or -0.80 if you using ponder.

**Comment by aki65** [comment]
The kyu-rank bot (which I didn't invent, I just ported it from katrain) is pretty independent of katago. It only uses katago's policy output (to order the quality of moves). In particular it doesn't calculate any winrates, so he has no clue when to resign. Therefore he never does. You have to end the game manually (e.g. after checking the winrate with real katago, which you obviously already did).

**Comment by HackYardo** [comment]
That's it, thanks!
