### ISSUE TITLE
in v1.5.1 lz can be removed

### ISSUE THREAD

**Issue by cryptsport** [aki65/aki65.github.io#22]
in v1.5.1 it is impossible to connect lz network. then lz can be excluded from the application

**Comment by aki65** [comment]
That will make the complete app crash if you select LZ nonetheless. But as I assume this is not a problem for you, I will do so.

**Comment by cryptsport** [comment]
Thank you so much! you can accidentally press the "switch to lz" button, can make it inactive in 1.5.1 (if it's easy, of course)?

**Comment by aki65** [comment]
I will check what's easier: preventing the crash or disabling the button ...

**Comment by aki65** [comment]
After adding the safety measures, I built the APK without LZ ... and it was a mere 300 bytes smaller (yes, less than 1 KB). As this is not worth the risks involved, I left LZ in for version 1.6.

**Comment by cryptsport** [comment]
OK, thanks!
