### ISSUE TITLE
About some additional custom settings in the config

### ISSUE THREAD

**Issue by Dreamkeeper66666** [aki65/aki65.github.io#23]
Hi, thanks for your amazing app! I am wondering if there could be some more custom settings in the config. Like (dynamic) PDA (to deal with the handicap games more properly), maxTime (to make the search time more flexible while playing against katago). By the way, how did you convert the orignal network to a smaller one? Can I do this on my own so that I am able to use some other networks? And could this optimized network be applied to the katago engine as well?  Thanks! @aki65

**Comment by aki65** [comment]
Yes, I can add a few more settings.

The original network was converted by a kind of 8-bit integer quantization (you can't do this on your own). This is useful for mobiles, since storage is often sparse and slow there and many devices have special HW for fast 8-bit computations. On a PC none of this holds true, so that the conversion doesn't make much sense for the katago engine.

**Comment by Dreamkeeper66666** [comment]
> Yes, I can add a few more settings.
> 
> The original network was converted by a kind of 8-bit integer quantization (you can't do this on your own). This is useful for mobiles, since storage is often sparse and slow there and many devices have special HW for fast 8-bit computations. On a PC none of this holds true, so that the conversion doesn't make much sense for the katago engine.

Thank you! Just out of curiosity, did you convert the network using tensorflow lite converter? Would you mind sharing the code for this part if it's not too complicated? Thanks!

**Comment by aki65** [comment]
Indeed, it's too complicated (see https://lifein19x19.com/viewtopic.php?p=263169#p263169)

**Comment by Dreamkeeper66666** [comment]
> Indeed, it's too complicated (see https://lifein19x19.com/viewtopic.php?p=263169#p263169)

Got it. Thanks!

**Comment by aki65** [comment]
I added PDA in version 1.6. The time can already be controlled in the UI settings.

**Comment by Dreamkeeper66666** [comment]
> I added PDA in version 1.6. The time can already be controlled in the UI settings.

Great! Thanks! It would be better if there is a dynamic PDA.

**Comment by aki65** [comment]
If you leave the field "PlayoutDoublingAdvantage" blank, then KG uses dynamic PDA. If you enter a number between -3.0 and 3.0, it will instead use the value you entered.

**Comment by Dreamkeeper66666** [comment]
What's the default value for the  dynamic PDA? By the way, I just tried to do the conversion using tf.lite.TFLiteConverter.from_session with the orignal scripts. However the output tflite file didn't get any smaller. 
And I got a lot of these...
` function_optimizer: function_optimizer did nothing. time = 0.005ms.`
So I just loaded your optimized network, it seems that the input and the output tensors are just some intermediate parameters which are kind of different from the original network. So did you modify the structure a little bit (or redefine the parematers)?

**Comment by aki65** [comment]
> So what's the default value for the dynamic PDA? Is it 0.045?  

Yes, dynamicPlayoutDoublingAdvantageCapPerOppLead is 0.045
From the documentation I concluded that it is not recommended to play around with this (except setting it to 0 to turn off dynamic PDA). Instead, if you are not satisfied with the dynamically calculated PDA for your game setting, you should use playoutDoublingAdvantage to override it.

> By the way, I just tried to do the conversion ...

This is complicated. I'm sorry, I don't have the time to give support here.

**Comment by Dreamkeeper66666** [comment]
> > So what's the default value for the dynamic PDA? Is it 0.045?
> 
> Yes, dynamicPlayoutDoublingAdvantageCapPerOppLead is 0.045
> From the documentation I concluded that it is not recommended to play around with this (except setting it to 0 to turn off dynamic PDA). Instead, if you are not satisfied with the dynamically calculated PDA for your game setting, you should use playoutDoublingAdvantage to override it.
> 
> > By the way, I just tried to do the conversion ...
> 
> This is complicated. I'm sorry, I don't have the time to give support here.

Thank you anyways!
