### ISSUE TITLE
 [feature suggestion] write&read the results of analyzing 

### ISSUE THREAD

**Issue by HackYardo** [aki65/aki65.github.io#27]
The analyzed results of different GUI are different, i.e. Sabaki can't show winrate graph when reading the analyzed results generated by KaTrain. They have no universal format.
Will BadukAI write&read analyzed results? What the format will be?

**Comment by aki65** [comment]
I will think about it. Regarding the format, I don't know of any standard how to do this, so I will have to invent something.

**Comment by HackYardo** [comment]
In my view, we could use the format of KataGo GTP Extension, and other GTP engines(i.e. LeelaZero, SAI) could just use its subset. 
How about kata-raw-nn SYMMETRY?

whiteWin (1 float)  - believed probability that white wins
whiteLoss (1 float) - believed probability that black wins
noResult (1 float)  - believed probability of noresult due to triple ko
whiteLead (1 float) - predicted number of points that white is ahead by (this is the preferred score value for user display).
whiteScoreSelfplay (1 float) - predicted mean score that would result from low-playout noisy selfplay (may be biased, Kata isn't fully score-maximizing).
whiteScoreSelfplaySq (1 float) - predicted mean square of score that would result via low-playout noisy selfplay
policy (boardXSize * boardYSize floats, including possibly NAN for illegal moves) - policy distribution for next move
policyPass (1 floats) - policy probability for the pass move
whiteOwnership (boardXSize * boardYSize floats) - predicted ownership by white (from -1 to 1).

**Comment by aki65** [comment]
BadukAI now writes and reads analysis results in release 1.9.0.

I updated index.html to reflect all the changes in release 1.9.0. In index_zh.html I only updated the numbers. It would be very nice if you could update the text in accordance with index.html.

**Comment by HackYardo** [comment]
I make a pull request

**Comment by aki65** [comment]
Thank you very much.
