### ISSUE TITLE
Qualcomm snapdragon 888 cannot use acceleration weights.

### ISSUE THREAD

**Issue by Fly143** [aki65/aki65.github.io#29]
Acceleration weight is not compatible with  snapdragon 888.There will be a wrong message.But it also works, just not that fast,Just like a regular one.Please see the attachment I uploaded for the wrong information.
![IMG_20210402_201534](https://user-images.githubusercontent.com/80356009/113414906-98cdf280-93f0-11eb-9b51-7aa2ac4b961f.jpg)

**Comment by Fly143** [comment]
The acceleration weights for loading are kata1-40b-s680.

**Comment by Fly143** [comment]
The acceleration weight for loading is kata1-40b-s680

**Comment by Fly143** [comment]
The acceleration weights for loading are kata1-40b-s680.

**Comment by aki65** [comment]
Yes, I have the same problem on my own new phone, also with Snapdragon 888. It seems that Qualcomm messed up the NPU driver, as the KG model can't run on NPU anymore (though it did so on all previous Snapdragon chipsets). Therefore it runs on CPU which makes it slow. 
I already sent a bug report. Moreover I'm trying to restructure the model, in order to circumvent the bugs. But I don't know yet if that will be possible at all ...

**Comment by aki65** [comment]
I made a new release 1.8.2 which resolves the problem.

**Comment by Fly143** [comment]
> I made a new release 1.8.2 which resolves the problem.
Thank you very much. To be able to solve annoying bugs so quickly. It's really good. Finally, thank you again.

**Comment by Fly143** [comment]
> I made a new release 1.8.2 which resolves the problem.

In addition, leelaz has stopped updating. Stayed at S287 forever. Can you optimize it, too? This may be a good memorial for everyone. @aki65

**Comment by aki65** [comment]
I have to work on the LZ networks anyway, since they also have massive performance problems on snapdragon 888 (unfortunately different ones than katago). While doing this, I can replace LZ286 with LZ287, but it may take some time to resolve these issues.

**Comment by aki65** [comment]
This is now included in release 1.9.0

**Comment by Fly143** [comment]
> This is now included in release 1.9.0

Thank you
