### ISSUE TITLE
in version 15 kyu-rank works differently

### ISSUE THREAD

**Issue by cryptpark** [aki65/aki65.github.io#3]
for example BadukAI v14 3d 15b - CS Zero 3d 7-3, BadukAI v15 3d 15b - CS Zero 3d 0-10. so it should be? all settings are the same.
also plays poorly against CS Zero 5k, BadukAI v15 3d 15b - CS Zero 5k 0-1.
BadukAI v15 3d 15b - CS Zero 11k 0-1
plays like a beginner. maybe there is some mistake?

**Comment by cryptpark** [comment]
made another new emulator, BadukAI KG black, 15b, 15p, against CS Zero 7d, after 4th move white winrate is about 0

**Comment by aki65** [comment]
Version 0.15 introduced a serious bug in the order of gtp commands. I fixed this in version 0.16 and hope everything is back to normal with this. Thanks for testing so much.

**Comment by cryptpark** [comment]
thank you so much!!!
