### ISSUE TITLE
Ask

### ISSUE THREAD

**Issue by Oltlm** [aki65/aki65.github.io#34]
Can we add support for GPU operations? If not, what are the obstacles?

**Comment by aki65** [comment]
The optimized networks in BadukAI use NNAPI for evaluation (if available), which is a hardware independent framework for fast neural network evaluation. The actual implementation depends on the manufacturer: If the GPU is the fastest way to run the network, he will use it. But more likely the specialized neural processing unit (NPU), that all modern devices have, will be faster and therefore be used.

**Comment by Oltlm** [comment]
Can't run GPU and NPU at the same time?



发自我的iPhone


------------------ Original ------------------
From: aki65 ***@***.***&gt;
Date: Tue,May 4,2021 5:47 AM
To: aki65/aki65.github.io ***@***.***&gt;
Cc: Oltlm ***@***.***&gt;, Author ***@***.***&gt;
Subject: Re: [aki65/aki65.github.io] Ask (#34)





 
The optimized networks in BadukAI use NNAPI for evaluation (if available), which is a hardware independent framework for fast neural network evaluation. The actual implementation depends on the manufacturer: If the GPU is the fastest way to run the network, he will use it. But more likely the specialized neural processing unit (NPU), that all modern devices have, will be faster and therefore be used.

**Comment by aki65** [comment]
It's possible. Whether it is efficient, depends on the hardware (as it causes a lot of additional data transfer via shared resources). If such a parallel approach increases speed, then the manufacturer will probably already implement the NNAPI interface in this way.

Generally speaking, you shouldn't expect too much from a phone's GPU in terms of neural network performance. They are designed for graphics, not for computing. Just look at the OpenCL compute scores of phones at geekbench: They are far lower than those of laptop or desktop GPUs.

**Comment by Oltlm** [comment]
在对于npu性能弱的处理器下，例高通848运用gpu是否会更快？

**Comment by Oltlm** [comment]
在ai性能低下处理器是否可以用gpu计算，例高通845

**Comment by aki65** [comment]
I don't have a SD 845 to test with, but if you provide some further information, I can try to figure out in which way the neural network is currently evaluated on your device.
1) Which android version do you have ?
2) How many visits per second do you currently get with the built-in 20b network ? (Easiest way to measure this is described here: [https://github.com/aki65/aki65.github.io/issues/10#issuecomment-749235931](url) )
3) How many visits per second do you get with the built-in 10b network ?

**Comment by aki65** [comment]
Extrapolating from the SD 845 results at ai-benchmark.com, these are the speeds I would expect.

Those benchmarks also show that involving the GPU would not gain anything, it is much slower. So I'm sorry, I don't see any possibility to get the network evaluation faster on your device.

As for IOS, I don't have a development environment for IOS (mac), so I can't do anything there. Moreover, there already exists an IOS app that runs katago and leelazero ( https://apps.apple.com/de/app/a-master-of-go/id1442035374 )

**Comment by Oltlm** [comment]
好的谢谢



---Original---
From: ***@***.***&gt;
Date: Sat, May 8, 2021 04:10 AM
To: ***@***.***&gt;;
Cc: ***@***.******@***.***&gt;;
Subject: Re: [aki65/aki65.github.io] Ask (#34)




 
Extrapolating from the SD 845 results at ai-benchmark.com, these are the speeds I would expect.
 
Those benchmarks also show that involving the GPU would not gain anything, it is much slower. So I'm sorry, I don't see any possibility to get the network evaluation faster on your device.
 
As for IOS, I don't have a development environment for IOS (mac), so I can't do anything there. Moreover, there already exists an IOS app that runs katago and leelazero ( https://apps.apple.com/de/app/a-master-of-go/id1442035374 )
