### ISSUE TITLE
offer optimized  6-block or 10-block katago weight

### ISSUE THREAD

**Issue by WindOfStorm** [aki65/aki65.github.io#35]
thanks for your  hard and wonderful work. here is a suggestion. many people  ，i  think, prefer a weight that is much  faster to  run,not that the stronger  the better. after  all, most of us is not beyond pro-level,and  6-block or 10-block weight  is enough  and  suitable.
so   could you  please offer a optimized 6-block or 10-block katago weight?looking forward to  your reply.

**Comment by aki65** [comment]
I provided an optimized 10b network in release 1.9.1

**Comment by WindOfStorm** [comment]
thank you very  very  very much.
