### ISSUE TITLE
New Teaching Mode

### ISSUE THREAD

**Issue by Fly143** [aki65/aki65.github.io#37]
Can players add a new teaching mode when playing with AI? When the lost points exceed the set limit, the AI will automatically delete and let the player choose again.Just like the software KaTrain on the computer.This will help the player to learn the AI idea better.
@aki65 
![1621342626439](https://user-images.githubusercontent.com/80356009/118654998-b4b01b00-b81b-11eb-99e3-faa5ebf17e72.jpg)

**Comment by aki65** [comment]
I will consider that for the next version.

For the time being, you can do it manually. With "winrate on play" enabled, you can monitor the points score during play, and if the score drops heavily after your last move, you can take it back by "undo".
