### ISSUE TITLE
Crash in launch

### ISSUE THREAD

**Issue by ivysrono** [aki65/aki65.github.io#39]
Android notetice : View in Full Screen.
Then baduk crash.
[Xiaomi Poco X3 GT - Full phone specifications](https://www.gsmarena.com/xiaomi_poco_x3_gt-10949.php)
[dotOS Android 11](https://www.droidontime.com/arm64)
Baduk_1.9, full and red.

**Comment by aki65** [comment]
Did you have something plugged into the usb port ? This causes the app to crash on android 11 due to a bug in the framework I use (so I can't help it).

**Comment by ivysrono** [comment]
> Did you have something plugged into the usb port ?
No

> crash on android 11

I used this APP on other 3 devices android 11 all, they are normal.

I guess it may coused by Shaped Screen, PocoX3GT is Punch Hole cutout Screen.

**Comment by aki65** [comment]
Normally, devices with punch hole have a page in the settings called "Full Screen" or similar. There you can configure for each app if it shall use fullscreen or not. You could try switching off fullscreen for BadukAI there.

**Comment by ivysrono** [comment]
It's ok in MIUI. So it may be ROM bug.
I will test it after 2 weeks for some reason.

**Comment by ivysrono** [comment]
Uninstall and reinstall solve this isuue.
Strange.
