### ISSUE TITLE
Whether ownership slow down node/second or not?  

### ISSUE THREAD

**Issue by HackYardo** [aki65/aki65.github.io#42]
I hear about it that the GTP command "ownership" could **slow down** analyze speed a lot, is it true in BadukAI?
How many times does BadukAI calculate ownership, **only once** after a ownership-query(a user hit "own" button), or **every time** meanwhile every analyze?

**Comment by aki65** [comment]
BadukAI "calculates" ownership within every analysis comnand (by "kata-analyze ... ownership true"), but there was no slowdown of nodes/second, when I added this feature.

**Comment by HackYardo** [comment]
Well, if I give KataGo a command "**genmove**", will it be faster than a command "**kata-analyze ...**"?

**Comment by aki65** [comment]
If you let them make the same number of visits/playouts, there will be no speed difference (at least I didn't notice any in BadukAI).

**Comment by HackYardo** [comment]
Oh, maybe my computer is too slow, there are two clearly different speeds on it.
