### ISSUE TITLE
How can I see realtime n/s in BadukAI?

### ISSUE THREAD

**Issue by bash99** [aki65/aki65.github.io#44]
So I can know whether hardware accelation is worked?

My device has a 768g soc.

**Comment by aki65** [comment]
You can measure n/s (which is practically same as visits/s if only a single position is considered) as follows:

Set thinking time to, say 30 seconds, load the attached sgf (after renaming it to test.sgf), tap "analyse all" and watch how high the visit count goes until it stops. Then divide the result by 30.

For a 768g I would expect HW acceleration to work and yield around 30 n/s for Katago 20b network.

[test.sgf.txt](https://github.com/aki65/aki65.github.io/files/7130058/test.sgf.txt)

**Comment by bash99** [comment]
Many thanks for reply and your great work.

I've got 2463 with katago 20b network, and 2512 with 10b network.
1275 with optizimed kata1-40b-s985.

So 768g can has 80 n/s with 20b; and 40 n/s with 40b? It's quick nice than my expect.
I can only got 144 n/s on GTX 1060 6G, and 64 n/s on vega 8 (5800H yoga 14s)

**Comment by bash99** [comment]
Can BadukAI remember last network load setting? 

I've found it always restore to 20b after restart.

**Comment by aki65** [comment]
BadukAI already remembers the last network, and on my device this works well. At the moment I have no idea why this wouldn't work for you. What about other settings, for example "thinking time" ? Are they remembered ?

**Comment by bash99** [comment]
> BadukAI already remembers the last network, and on my device this works well. At the moment I have no idea why this wouldn't work for you. What about other settings, for example "thinking time" ? Are they remembered ?

Sorry，it's maybe something wrong in my previous step (perhaps a force close) , it works now.
