### ISSUE TITLE
a bit gotcha because of screen not enough long

### ISSUE THREAD

**Issue by HackYardo** [aki65/aki65.github.io#46]
How my **W winrate** and **score-lead** be displayed:
> <del>W winrate:</del>     
<del>97.3%</del>

><del>score-lead:</del>
<del>11.2</del>

Only a half of string could be displayed, the other half disappear.

**Comment by aki65** [comment]
I'm very sorry for that. 

I had to decrease the horizontal space for winrate and score-lead slightly to gain some space for the clock, which now appears right to the score-lead (if it is running). To compensate, I made the texts for winrate and score-lead shorter, and this worked on all of my phones (even on the 5'' display). 

But with your combination of screen and font size the texts/numbers for winrate and score-lead are still too wide, so they are broken into two lines, but the height of the blue area is not intended for two lines, so you see only part of the texts/numbers.

As a quick fix you could try to use a smaller font (usually there is a system setting like "text size" or similar to control that).

**Comment by HackYardo** [comment]
Thanks, it works.
