### ISSUE TITLE
Do you need a Chinese translation?

### ISSUE THREAD

**Issue by noword** [aki65/aki65.github.io#47]
The Chinese was translated with google?

**Comment by aki65** [comment]
For the chinese translations the current "workflow" is as follows:

When I publish a new release, I use translations from google and deepl for the new texts which have been added in the release. Additionally, I update the file translations.py in this repository which includes all translations used in the app. Then Ya Tienna (and sometimes also ivysrono) look over the changes in this file and correct the ugly ones. Afterwards I merge translations.py and use it in the app for the next release.

For a release (for example 1.11) this means:
New texts (in this case those concerning time management) have "google quality".
All other texts should be ok (as they were already in the app in release 1.10 and have been corrected).

So for chinese translations the situation is quite ok. 

But the korean and japanese translations are all completely on "google level" ...

**Comment by noword** [comment]
Thanks for replying.

score-lead: 棋领先目， feels a little weird，so I thought it was machine translated. 
"领先目数" is better.

**Comment by aki65** [comment]
Yes, "score-lead" translation was bad, Ya Tienna has already corrected it to 目差 in translations.py (for the next release). If that is also ok, I would prefer it, because it's shorter and the space in this row is quite narrow.

**Comment by HackYardo** [comment]
@aki65 you can add a **zh branch**, so that @noword , @ivysrono and I can translate better.

**Comment by ivysrono** [comment]
BTW, you can close #15 and #33 , which are useless.

**Comment by VK3002** [comment]
Hi aki65,
Here are some suggestions on translation.

At Settings>Set board appearance>Board appearance

---
"Board appearance" should be "棋盘设置"
"Stones numbered" should be "显示棋子手数"
"Show next move marker" should be "显示下一手标记"

"All stones in same colour" can be translated into "单色棋", "同色棋" or "所有棋子同色".Just choose one of the translations above.

---
theme
"white stone" should be "白棋"
"black stone" should be "黑棋"

---
"close" should be "关闭"

**Comment by aki65** [comment]
Thanks for the translations. I integrated them in https://github.com/aki65/aki65.github.io/releases/tag/v1.19.26
