### ISSUE TITLE
How to know number of capture stones?

### ISSUE THREAD

**Issue by HackYardo** [aki65/aki65.github.io#48]
Whenever to evaluate a GO game, the numbers of capture stones of both players must be counted. However, it seems that BadukAI doesn't display the numbers and has no spare space to show.
In my view, the numbers can be placed with "komi" in the setting menu.

**Comment by aki65** [comment]
I added a display of the captures in version 1.12. This release also includes a lot of other changes, so I had to adapt index.html. It would be very nice if you could update index_zh.html accordingly and go over the new translations in translations.py

**Comment by HackYardo** [comment]
Awesome update!
I see it on my phone and will make a request pull by my laptop soon.
By the way, there are several details may helpful.
- Is "load empty board" the same to "clear_board" in the GTP commands?
- What's the meaning of "save to same file"?
- Could "detect ... from image" detect the move number on stones? (some software could export image with move numbers on stone and captures vertex bellow the board, for example q5Go@github)

**Comment by HackYardo** [comment]
I'm sorry I didn't see release 1.12.0 five minutes ago, so you don't need to reply my questions. I can know the answers by using the new 1.12.0 release.

**Comment by aki65** [comment]
Thank you very much for translating so fast.

**Comment by HackYardo** [comment]
You can @me to translate in release page, it seems a new feature of github.
