### ISSUE TITLE
Snapdragon 778G is not optimized?

### ISSUE THREAD

**Issue by bash99** [aki65/aki65.github.io#49]
Just test Baduk on it, only got 20n/s for katago 20b, which is much slower than 768G (80n/s).

Anyone can confirm? 

My device is Vivo T1.

**Comment by aki65** [comment]
778G has brand new Hexagon 770 DSP, so it certainly has a new NNAPI driver (other than 768G). So possibly
a) This driver is buggy and can't load the KataGo network (then BadukAI would fall back on CPU)
b) This driver has a performance bottleneck which slows down BadukAI

Both of these have happened before with the first generation of Qualcomm NNAPI drivers for new hardware ...

**Comment by bash99** [comment]
I got it, I'll report back if some update solve this problem.

**Comment by aki65** [comment]
You could try the 40b network from release 1.13.2, where I worked around some bugs in the new NNAPI driver for the Snapdragon 888. Maybe the driver on 778G has similar issues, then this network could also improve things on your vivo (just a chance, but it doesn't hurt to try).

**Comment by bash99** [comment]
> You could try the 40b network from release 1.13.2, where I worked around some bugs in the new NNAPI driver for the Snapdragon 888. Maybe the driver on 778G has similar issues, then this network could also improve things on your vivo (just a chance, but it doesn't hurt to try).

It's worked!  I've got 1800 visit in 30 seconds, so it's 60 n/s for 778G.
Thanks for your great work.
