### ISSUE TITLE
Several bugs in ver1.12.0

### ISSUE THREAD

**Issue by HackYardo** [aki65/aki65.github.io#51]
- Analyzer and AI-player treat Black as White and treat White as Black after editing static position sometimes.
  - ![inverse1](https://user-images.githubusercontent.com/57677458/141220505-fb39b126-9292-4b57-aa0c-94357589f0f8.png)
  - ![inverse2](https://user-images.githubusercontent.com/57677458/141221650-024e2f75-d704-4d83-8b52-8d4569da76cf.png)

- Detecter doesn't remove illegal stones automatically.
  - ![illegal](https://user-images.githubusercontent.com/57677458/141221695-85741708-694a-4163-9e05-97c76b998ce0.png)

**Comment by aki65** [comment]
Thanks for reporting this.

Such problems can occur if the starting position contains stones with no liberties. It seems trivial to remove them, but that's not always true. Look at this position:
![5D79E670-F57C-4CFD-B0AF-63B38E1283E8](https://user-images.githubusercontent.com/46307312/141360156-b5b30afd-6b2a-4ab8-b89b-f720337b2aeb.jpeg)
Which stone should be removed ? The black one ? The white one ? Both ?

Currently, the detector doesn't remove any stones (it just detects), as you already observed yourself. Neither does the editor (it just edits). But when the play starts, something has to be done. Unfortunately the AI and the user interface use different algorithms to decide which stones to remove. So sometimes they don't reach the same conclusion. Then the position you see will differ from the position that AI sees. This will cause evaluations and ownerships that don't match the position you see, just as in your example.

I will synchronize the removal decisions between AI and user interface in the next version. For the time being, I can only suggest that you remove stones without liberties manually before starting play. Then such problems should not occur.

**Comment by HackYardo** [comment]
I find some small flaws, for an example:
- "second/move" and "maxPlayout/move in analyze" in "AI time setting" in "time manage", they are setting in analyzing and **not** in playing. But it looks like setting in playing...

**Comment by aki65** [comment]
"Seconds/move" is for both: analyzing and playing.

**Comment by HackYardo** [comment]
I check index(zh).html and translation.py for one more time, I find a question. In "how to adjust AI strength..." section, why LeelaZero can't load weak network to adjust strength?  I think it should be add into the section too.

**Comment by HackYardo** [comment]
@aki65 For someone who can not beat KG-6b-0visit, he can load LZ-6b to win.

**Comment by aki65** [comment]
LeelaZero can only load optimized models in BadukAI. This is because the LZ software structure only allows for one backend, and I need my tflite backend to load the strong optimized models. So there is no standard CPU backend anymore to load the original LZ models.

Luckily, this is not needed to get a beatable network: KataGo has a lot of 6b networks and the very early ones are so weak, that everybody with a little playing experience should be able to beat them.

**Comment by aki65** [comment]
@HackYardo Thank you very much for updating the translations.

**Comment by HackYardo** [comment]
Why can't I choose network file? It's my first time to load network. Because weak bots from KaTrain can not resign, I try play with weak KataGo networks.
![CanNotChooseNetworkFile](https://user-images.githubusercontent.com/57677458/144337907-f9062145-1272-4ec1-bfbc-9c88013712bb.png)

**Comment by HackYardo** [comment]
- I can load **.txt.gz file** after tap **choose \*.tfile**. Maybe the two buttons, i.e. the "choose \*txt/bin.gz" button and the "choose \*.tfile" button, are reversed.
- It seems that the weak KataGo networks are too weak to analyze positions, it places stones wherever it wants and resigns games whenever it likes.
  - But it does much well on 9*9 board.
  - 
![_20211202_095234](https://user-images.githubusercontent.com/57677458/144344060-128aa571-b0f0-4df5-904a-56b00997668a.JPG)
![_20211202_095301](https://user-images.githubusercontent.com/57677458/144344066-30dd6b2c-c93d-4922-8b07-f5f1f6298bab.JPG)

**Comment by aki65** [comment]
The system file pickers (that I have to use now) can't filter by file name extension, they can only filter by MIME type. For ".txt.gz/.bin.gz" I filter by MIME type "application/gzip" (which comprises all gzip'ed files), for ".tflite" I filter by "application/octet-stream" (which comprises all binary files for which there is no special MIME type). Not perfect, but it's the best I can do.

Now comes the problem: MIME type "application/gzip" is quite new, so some vendors (especially on older phones) have not implemented that type in their system file pickers. In that case, a .txt.gz file has no special MIME type, so its MIME type becomes "application/octet-stream". Therefore, it can be selected with the ".tflite" button, but not with the ".txt.gz/.bin.gz" button. 

I'm sorry, but I can't help that because I don't know which vendors have been lazy on which phones ...

**Comment by HackYardo** [comment]
I start a project for the [nonstandard Go](https://github.com/HackYardo/VastGo#nonstandard-go) games for fun, and it now can place stones after mouse's clicking. Meanwhile BadukAI will [add](https://www.lifein19x19.com/viewtopic.php?f=18&t=17784&start=360) one color Go. I have to say, time moves swiftly onward.(I'm not godave89) 😆

**Comment by aki65** [comment]
I made a new release 1.13.0 which includes one color go and bugfixes for the editing of the starting position (and some other new features). As usual, I had to update translations.py and index.html accordingly. It would be very nice if you could check the changes in translations.py und update index_zh.html.

**Comment by aki65** [comment]
Thank you very much for the quick translation.

**Comment by HackYardo** [comment]
In the position
```
  B
B w B
W b W
  W
```
, how does BadukAI choose from `b` `w`?

**Comment by aki65** [comment]
When you create a starting position by "add B stone" and "add W stone", then if a stone has no liberties left, it is deleted immediately (just as if the setup stones were moves in a game).
So an ambiguous position (like the one you mentioned) can not occur anymore.

**Comment by HackYardo** [comment]
Sorry for the incomplete question. When detect stones from image, how choose the ambiguous pair stones?

**Comment by aki65** [comment]
In that case the white one is removed (just a random choice: The removal of stones without liberties starts with white, and when the white one is gone, the black one has a liberty, so remains on the board).

**Comment by HackYardo** [comment]
It seems that bugs in 1.12 has gone in 1.13, so I close the issue.
