### ISSUE TITLE
[question]where is the .tflite download?

### ISSUE THREAD

**Issue by 1067511899** [aki65/aki65.github.io#52]
From https://katagotraining.org/networks/,I only find the .bin.gz files,but not find any tflite files.

where can I find those files?

thanks.

**Comment by HackYardo** [comment]
Every model has a TF Weight and a Network file, the TF is for you.

**Comment by aki65** [comment]
There are two kinds of KataGo models:

1) The original models from https://katagotraining.org/networks:
These consist of only one file (the .bin.gz). So, in BadukAI tap "Choose *.txt.gz / *.bin.gz", select this file, then tap "Load".

2) Optimized versions of the original models (they are much faster in BadukAI):
They consist of two files (.bin.gz and .tflite). You can download the most recent optimized 40b network from https://github.com/aki65/aki65.github.io/releases/tag/v1.10.1 and the most recent optimized 60b network from https://github.com/aki65/aki65.github.io/releases/tag/v1.10.2. Ignore the instructions there, they are for an older version of BadukAI. In BadukAI 1.12 tap "Choose *.txt.gz / *.bin.gz", select the .bin.gz, then tap "Choose *.tflite", select the .tflite, then tap "Load".

**Comment by 1067511899** [comment]
Thanks.I 've solved the problem.
