### ISSUE TITLE
katago

### ISSUE THREAD

**Issue by ugvvff** [aki65/aki65.github.io#60]
katago最近引擎更新，似乎提升很大，什么时候能够应用到badukai

**Comment by ugvvff** [comment]
引擎实力提升很大

**Comment by ugvvff** [comment]
联发科9000不支持加速，是否可以适配？

**Comment by aki65** [comment]
badukai 1.15已经包括katago 11.0的最新功能。
至于Dimensity 9000，你可以用 https://github.com/aki65/aki65.github.io/releases/tag/v1.15.1，
用新的配置选项 "使用特定的NPU加速器" 尝试不同的加速器。
如果它们都不工作，请分享安卓系统日志，以便我可以寻找错误信息。
