### ISSUE TITLE
Not even wrong moves played by 8 kyu KataGo

### ISSUE THREAD

**Issue by HackYardo** [aki65/aki65.github.io#62]
![IMG_20220528_104233](https://user-images.githubusercontent.com/57677458/170809675-d101d4ed-f11c-4850-b203-817e8cdf9043.jpg)

Is it the mistake of BadukAI or KaTrain?

**Comment by HackYardo** [comment]
![image](https://user-images.githubusercontent.com/57677458/170873103-f8af94f4-92a1-4260-b179-ad438c2a107e.png)

I just try it in KaTrain, it played slower and weaker than BadukAI, but no suicide moves.

**Comment by HackYardo** [comment]
https://github.com/aki65/aki65.github.io/issues/4#issuecomment-723693203 Only excluded multi stones suicide? Perhaps some side effects here.

**Comment by aki65** [comment]
The marked move is not suicide, it is just self-atari, so no rule issues here.

Technically speaking, it is not even a bad move. It has practically the same winning probability as all other white moves in this position (namely 0%). So, for AI there is no difference between them. It is just human thinking that "losing by 50 is better than losing by 200", but AI doesn't see it that way.

**Comment by HackYardo** [comment]
Oh, I understand 👌 
Another question, why kyu bot of KaTrain could pass successively to end a game while BadukAI dont :thinking:

**Comment by aki65** [comment]
When I implemented the kyu-rank bot a long time ago, I wanted to get it running quickly (for the next release), so I omitted the code for selecting a pass when appropriate, since it wasn't absolutely necessary to get a game going. 
But it's probably a good idea to add it now.

**Comment by HackYardo** [comment]
Thanks a ton.
