### ISSUE TITLE
could not open some “.sgf” file

### ISSUE THREAD

**Issue by otcbashen** [aki65/aki65.github.io#65]
badukai could not open some “.sgf” file，other app(GriderMaster,droidpiggy.weiqi) can open it，
for example:
1、
(;CA[gb2312]AB[is][fs][fq][eq][dq][cq][cr][hr]AW[br][bq][bo][cp][dp][ep][fp][gp]
[hp][ip][iq][ir][kr][hs]AP[MultiGo:4.4.4]SZ[19]AB[hq]MULTIGOGM[1]
;B[er];W[ds];B[cs];W[gr];B[gq])
2、(;GM[1]AP[StoneBase:SGFParser.3.0]SZ[19]GN[ ]HA[0]EV[李昌镐精讲围棋死活1]SO[《李昌镐围棋基础训练》初级篇、提高篇]US[阿浩]AB[ap][bp][cp][dq][eq][fq][gr][cr]AW[dr][aq][bq][cq][br][bs]C[黑先]
;B[ds];W[cs];B[es])
3、
(;CA[gb2312]GM[1]AB[ns][or][qr][pq][rq]AW[lr][nr][nq][qq][op][qp][rp][qo]PL[B]C[第16题 黑先

经常看到的棋形。]
AP[MultiGo:4.4.4]SZ[19]FF[3]GN[《棋经众妙》活之部第16题]RE[黑先活]US[林元美著、桥本宇太郎解说]
SO[《棋经众妙》活之部]MULTIGOGM[1]
;B[sq]C[黑1立下是手筋，黑棋不死。]N[正解];W[rs];B[rr];W[oq];B[ss]LB[sr:A][qs:B]
C[白如2、4攻击，则黑5扑。次白若A位提取，则黑B打弄成胀牯牛。

手顺中，白2如单下在4位，则黑2虎即可。])

thanks！

**Comment by aki65** [comment]
The second example can be loaded on my phone, so I can't tell you what went wrong there.

The first and third example show a bug: BadukAI accepts only tags upto 8 characters, but MULTIGOGM has 9. I will fix that, but for the time being you can just delete "MULTIGOGM[1]" from the examples with a text editor, then they can be loaded.

**Comment by otcbashen** [comment]
The second example can be opened through "load sgf from clipboard",but it can not be opened through "load sgf from storage".
How can I send the SGF files for these three issues to you？

**Comment by aki65** [comment]
You can attach them to a comment here.

**Comment by otcbashen** [comment]
Thanks,i have attach them here:
[example01.sgf.zip](https://github.com/aki65/aki65.github.io/files/9182185/example01.sgf.zip)
[example02.sgf.zip](https://github.com/aki65/aki65.github.io/files/9182188/example02.sgf.zip)
[example03.sgf.zip](https://github.com/aki65/aki65.github.io/files/9182192/example03.sgf.zip)

**Comment by aki65** [comment]
The second example doesn't include its character encoding (no CA tag). So BadukAI assumes the most common encoding (UTF-8). But the file is not UTF-8 encoded, it's gb2312 encoded. Therefore reading fails. You can fix that by inserting CA[gb2312] at the beginning of the file (just like the other two examples), then it can be loaded.

Reading from clipboard works, since in this case the SGF is directly passed as text to BadukAI (no character encoding involved).

I can't do anything about this in BadukAI, it's a problem of the software that created the SGF.

**Comment by aki65** [comment]
I can open example04.sgf as file and by clipboard.

**Comment by otcbashen** [comment]
thanks,example04 is ok after restart my phone.
example01,02,03  could not be open as file.

**Comment by otcbashen** [comment]
I have another try,all my example can be opened by “crazy stone”,Thank you for your efforts.

**Comment by otcbashen** [comment]
Thanks a lot.Expect BadukAI to get better and better.
