### ISSUE TITLE
Add Tsumego frame like Lizziezy

### ISSUE THREAD

**Issue by otcbashen** [aki65/aki65.github.io#66]
Add Tsumego frame like Lizziezy。
![IMG_20220720_145820](https://user-images.githubusercontent.com/109559896/179917514-e2db3d68-16fe-4c1c-b12e-d64294aa7d03.jpg)

**Comment by aki65** [comment]
Such a feature exists already, see https://aki65.github.io/#top_row

**Comment by otcbashen** [comment]
it is“By tapping the dashed rectangle in the top row you can restrict AI analysis to a region (which consists of a rectangle plus additional points)”？

**Comment by otcbashen** [comment]
“By tapping the dashed rectangle in the top row you can restrict AI analysis to a region (which consists of a rectangle plus additional points)”，i see,thanks.

**Comment by otcbashen** [comment]
is this“By tapping the dashed rectangle in the top row you can restrict AI analysis to a region (which consists of a rectangle plus additional points)”？

**Comment by aki65** [comment]
Yes, that's it.

**Comment by otcbashen** [comment]
thanks

**Comment by otcbashen** [comment]
thanks a lot

**Comment by otcbashen** [comment]
thanks a lot
