### ISSUE TITLE
Bug: Not show all in full screen view

### ISSUE THREAD

**Issue by ivysrono** [aki65/aki65.github.io#67]
1.17.0
Android12

My rom doesn't has settings called "Full Screen" or similar to config each app.
After several times pic1, then show pic2, not show complete.
![Screenshot_20220730-213624_BadukAI](https://user-images.githubusercontent.com/2649544/182008437-29ea81ff-3ebe-43c9-90cb-8d457c1f1f09.png)

Top and bottom display incomplete：
![Screenshot_20220730-213636_BadukAI](https://user-images.githubusercontent.com/2649544/182008439-7fff56e7-a371-452f-8034-c4249da9d75a.png)

**Comment by aki65** [comment]
Fullscreen mode is a delicate affair on android. Its handling differs a lot between roms:

1) On my Xiaomi Mi 11 with MIUI 13 there is an individual fullscreen switch for each app. But for most apps (including BadukAI) the switch has no effect at all ....

2) On a Realme GT 2 Pro with RealmeUI 3 (which I could use for a few days) there is also an individual fullscreen switch for each app and it worked for BadukAI: The app showed fine using the whole screen.

3) Now your rom introduces a third variation: It seems that the OS tells BadukAI to use the whole screen (as expected in fullscreen mode) and it does so. But then the OS displays a status bar (without status information) at the top and a navigation bar at the bottom which cover parts of BadukAI, so it seems incomplete. Therefore I don't see BadukAI at fault here. And even if it was, all the fullscreen stuff is handled automatically by the UI framework that Is used, and I can't modify that. So I am sorry, I don't think, I can do anything here.
