### ISSUE TITLE
choose image to load sgf, get stuck

### ISSUE THREAD

**Issue by HackYardo** [aki65/aki65.github.io#72]
After choose a image, BadukAI is always parsing, no matter what image is.

**Comment by aki65** [comment]
It works fine on all of my devices. Did it work for you with version 1.17 ?

**Comment by HackYardo** [comment]
It depends on the app which opens images, if use the default app, nothing wrong, if use another app(https://www.diune.com/) to open image, it just get stuck. v1.17 is fine.
