### ISSUE TITLE
1.18版本无法打开部分sgf文件

### ISSUE THREAD

**Issue by otcbashen** [aki65/aki65.github.io#74]
1.18版本无法打开部分sgf文件，请见附件，sgf录入软件为“围棋宝典”，部分黑先手的sgf无法打开，白先手的都可以。
麻烦检查一下，感谢。
[可以打开的sgf.zip](https://github.com/aki65/aki65.github.io/files/9605571/sgf.zip)
[无法打开sgf.zip](https://github.com/aki65/aki65.github.io/files/9605574/sgf.zip)

**Comment by otcbashen** [comment]
[可以打开的sgf.zip](https://github.com/aki65/aki65.github.io/files/9605551/sgf.zip)
[无法打开sgf.zip](https://github.com/aki65/aki65.github.io/files/9605552/sgf.zip)
附件在此处

**Comment by aki65** [comment]
sgf 文件包含一个“PL”标签，表示谁先玩，所以它必须是“PL[W]”或“PL[B]”。在白色开始的文件中，它是正确的。但是在黑色开始的文件中，它是“PL[X]”而不是“PL[B]”. 这就是 BadukAI 无法打开它们的原因。我将在下一个版本中处理这个问题，但实际上这个问题应该在 “围棋宝典” 中修复.

**Comment by fxb6666** [comment]
> sgf 文件包含一个“PL”标签，表示谁先玩，所以它必须是“PL[W]”或“PL[B]”。在白色开始的文件中，它是正确的。但是在黑色开始的文件中，它是“PL[X]”而不是“PL[B]”. 这就是 BadukAI 无法打开它们的原因。我将在下一个版本中处理这个问题，但实际上这个问题应该在 “围棋宝典” 中修复.

除此之外，sgf文件中的N[]和C[]含有中文字符也会导致打开sgf文件时出错
![Screenshot_20220925_211845](https://user-images.githubusercontent.com/102399040/192145718-502df1c7-b35f-402e-8fb6-da979f913699.jpg)

**Comment by otcbashen** [comment]
收到，非常感谢，我试着联系下“围棋宝典”的作者，把这个问题反馈给他，再次感谢您的恢复！

**Comment by otcbashen** [comment]
close
