### ISSUE TITLE
I need the original file of leelamaster gx78 (gz file)

### ISSUE THREAD

**Issue by Gengzi-Isu** [aki65/aki65.github.io#76]
Greetings。I'm sorry to trouble you, but the google link provided by YuanQuan in github has expired, and I can't get the weight files he made. But I'm still committed to collecting his human weight. I see that gx78 weight is provided in version 1.9.0 of your app, but it is specially designed for your app. I'd like to ask you for this original weight, if I may. Thank you!

**Comment by aki65** [comment]
I added the original .gz to release 1.9.0

**Comment by Gengzi-Isu** [comment]
It helped me a lot. thank you
