### ISSUE TITLE
Problems with Qualcomm Snapdragon 8gen2

### ISSUE THREAD

**Issue by Fly143** [aki65/aki65.github.io#77]
In a new phone, the optimized weight cannot be used, and its speed is very slow.The phone model is Mi 13 pro, the MIUI version is 14.0.8, and it is Android 13.The processor is Qualcomm Snapdragon 8gen2.

**Comment by aki65** [comment]
Yes, this was observed by others, too. My comment is here: https://www.lifein19x19.com/viewtopic.php?p=276210&sid=ad6a192525e50dad5bb6c4dd0a2d9583#p276210

**Comment by ugvvff** [comment]
您有没有骁龙8➕运行40b权重速度多块的数据？骁龙865在使用您发布最新的权重能够正常运行了，在没有棋子的情况下大概每秒30po

**Comment by aki65** [comment]
非常感谢您的反馈。
对于空板上的 40b 重量，我只有来自我自己设备的数据：
SD 888：230 次访问/秒
SD 8+ 第 1 代：430 次访问/秒

**Comment by ugvvff** [comment]
是否有不是空盘的数据，就是有棋时的数据？空盘情况下与非空盘下速度差别挺大的不知道为什么

**Comment by aki65** [comment]
当KataGo访问一个位置时，它会检查它是否已经访问过另一个位置，该位置与当前位置对称。在这种情况下，它会反映另一个位置的已知网络结果（而不是评估网络），这就节省了大量的时间。因此，游戏树中的位置越对称，每秒得到的访问量就越多。而空棋盘是这种效应的最极端例子。
在一个中盘位置（如附图），数字是。
SD 888: 170次/秒
SD 8+ gen 1: 340次/秒

[test.sgf.txt](https://github.com/aki65/aki65.github.io/files/10523803/test.sgf.txt)

**Comment by ugvvff** [comment]
高通8gen2的npu已经支持了int4(目前首款支持int4的手机处理器)，后续是否能用到此软件？如果能用到int4，在同处理器下int4会比int8更快吧？但是我在查资料时并没有说骁龙8gen2的int4比int8更快，只是提出能耗比更高。先目前骁龙8gen2的nnapi分数异常，会不会是高通在8gen2更换了接口？但是我并没有查到此资料是否更换。我觉得不太像是驱动没有做，因为在例如拍照时能够正常调用npu(ai摄影)。

**Comment by aki65** [comment]
int4 比 int8 产生更多的量化误差。 这对于某些类型的网络是可以接受的，例如分类网络，其中唯一重要的是哪个结果数字最高。 但 KataGo 不同：这里每个值都很重要，因为它指导搜索、显示胜率、分数等。所以我不希望 int4 为 KataGo 产生可接受的结果。
snapdragon 8 gen 2 上的 NPU 工作正常，这一点毫无疑问。 但似乎，NNAPI 实现目前不使用它，而只在 CPU 上运行。
AI 摄影可能效果很好，因为它不使用 NNAPI，而是使用 NPU 的其他一些接口。
对于 BadukAI，我还致力于使用（高通特定的）替代 NNAPI。 但目前还不清楚，这是否会奏效......

**Comment by ugvvff** [comment]
此外骁龙8Gen2还是首个商用部署INT4精度的移动平台。之所以支持INT4,是因为骁龙8Gen2依靠QualcommAlStudio可以让INT4做到与INT8相似的精度，并大大降低功耗。从现场来看INT4与INT8实现的效果确实几乎没有任何差别。这是我从网上找的一段话，指出int4能够与int8相似精度，到底能够多相似不清楚，后面是否考虑能够尝试一下？如果以后nnapi都不能够使用，那还有没有其他接口能使软件运行到npu上？

**Comment by aki65** [comment]
@Fly143 
Concerning Snapdragon 8 Gen 2, please try the latest test release: https://github.com/aki65/aki65.github.io/releases/tag/v1.18.4

**Comment by Fly143** [comment]
> @Fly143 关于Snapdragon 8 Gen 2，请尝试最新的测试版：https://github.com/aki65/aki65.github.io/releases/tag/v1.18.4

@aki65 Thank you very much, I did a simple test, both in the initial state and in the middle of the game, and reached 5300v in 10 seconds with 2 threads

**Comment by Fly143** [comment]
> 

Different conditions have different speeds, sometimes reaching 6000v in 10 seconds

**Comment by ugvvff** [comment]
谢谢您的工作能使katago能在8gen2npu上正常运行。后面作者是否有时间尝试做一个能够支持int4的版本？因为高通表示在他们某一技术下能使int4达到与int8相似精度(我还是想尝试一下，如果真有差距我能去测试一下大概能有多大差距，差距是否能够接受)，因为在之后可能会有大批处理器能够支持int4，如果真如高通所说能使int4达到与int8相似精度(如果高通没有这个技术确实没有尝试的必要但是现在我觉得可以尝试一下，当然这取决于你)那么在手机上的katago又是一个大进步。感谢您为手机版katago一直以来的工作

**Comment by Fly143** [comment]
@aki65 In badukai, the speed can reach 500v/s. When I tried to benchmark with badukai's libkatag.so in termux, there was an accident, the speed became abnormal, only 10v/s, how should I solve it?
![Uploading Screenshot_2023-02-20-09-03-45-116_com.termux.jpg…]()

**Comment by smilefox76** [comment]
I tested new release.
It works very well on Qualcomm Snapdragon 8gen2.
This release is fast and strong on my redmi  K60 pro.
Thanks a lot.  And I like your software.
Thanks again

**Comment by aki65** [comment]
"use SNPE on GPU"
That means that it's not using the DSP, therefore it's so slow. We could try to find out why this happens in termux, but it's not worth the effort, because the benchmark won't run anyway. I tried it myself and it creates two backend instances. This is a good idea if a backend represents a GPU. But for the SNPE backend on DSP, this leads to a double initialization and SNPE can't handle that, so the benchmark crashes.
I assume that you tried the benchmark because you wanted to measure playouts / s instead of visits / s. That can also be done with BadukAI:
Set MaxPlayouts to a large number (e.g. 10.000) in settings and then let KataGo play a move. Measure the time until it plays with your stop watch and you get the time needed for 10.000 playouts. The time measurement can't be done very accurately this way, but with many playouts the error is acceptable.

**Comment by aki65** [comment]
@ugvvff 
高通公司的准确性声明只适用于某些类型的网络（当然，他们的营销人员从未提及这一点），而KataGo并不是其中之一。
即使我们忽略了所有的计算错误，只要考虑到这一点: KataGo的网络的一个输出是当前的分数（以分计）。如果这个输出是INT4，那么就只有16个可能的分数。即使我们说-30和+30之间的分数就足够了，这仍然意味着4分的不准确性，即使是在晚期的残局。没有人会接受这一点......

**Comment by ugvvff** [comment]
好的，谢谢

**Comment by ugvvff** [comment]
作者有没有兴趣移植katago版的五子棋，电脑端叫katagomo，在五子棋ai软件中几乎是最强的



---Original---
From: ***@***.***&gt;
Date: Tue, Feb 21, 2023 04:11 AM
To: ***@***.***&gt;;
Cc: ***@***.******@***.***&gt;;
Subject: Re: [aki65/aki65.github.io] Problems with Qualcomm Snapdragon 8gen2(Issue #77)




 
@ugvvff
 高通公司的准确性声明只适用于某些类型的网络（当然，他们的营销人员从未提及这一点），而KataGo并不是其中之一。
 即使我们忽略了所有的计算错误，只要考虑到这一点: KataGo的网络的一个输出是当前的分数（以分计）。如果这个输出是INT4，那么就只有16个可能的分数。即使我们说-30和+30之间的分数就足够了，这仍然意味着4分的不准确性，即使是在晚期的残局。没有人会接受这一点......

**Comment by uestccokey** [comment]
Are 18b weights loaded on the latest 8Gen3 processor?

**Comment by Fly143** [comment]
> Are 18b weights loaded on the latest 8Gen3 processor?

At present, I do not have an 8Gen3 device, so I do not know whether it is possible to load the 18b weights on the 8Gen3 device.

**Comment by aki65** [comment]
There is a separate issue for 8 gen 3 now (#107).
