### ISSUE TITLE
Toggling analysis visibility

### ISSUE THREAD

**Issue by happapa** [aki65/aki65.github.io#78]
Hi,

I love using your app, but I sometimes find myself getting overwhelmed by all the information that is being shown to me. All the green, red, and yellow circles can be a bit distracting if I'm trying to read ahead the board position in my head. Have you ever considered adding a button that temporarily toggles the visibility of the analysis and just shows you the clean board? Something like the current 'own' button, but without the territory markings.

**Comment by aki65** [comment]
That's a good idea. I have put this onto my TODO list. Meanwhile you can toggle the visibility of the analysis by this "trick":
1) Turn it off by tapping "pass", then "<", then ">"
The pass creates a new position (but with the same stones). So when you leave it (by "<") and then return (by ">"), there is no saved analysis to be loaded. Thus there are no analysis circles on the board.
2) Turn it on again by tapping "Undo move"
By this you return to the original position (and delete the variation created by the "pass"), so the analysis is reloaded.

**Comment by bltoby** [comment]
Hope you kann add this feature soon, this is so essential IMHO.

Thanks for your great

**Comment by aki65** [comment]
This is now included in the latest test release https://github.com/aki65/aki65.github.io/releases/tag/v1.18.5 . Toggle with the button with the green circle in the top row.
