### ISSUE TITLE
能否增加“显示手数”的功能？

### ISSUE THREAD

**Issue by otcbashen** [aki65/aki65.github.io#79]
能否增加“显示手数”的功能？谢谢。

**Comment by aki65** [comment]
剩下的空位不多，但我会努力。

**Comment by aki65** [comment]
这一点现在已经包括在最新的测试版本中  https://github.com/aki65/aki65.github.io/releases/tag/v1.18.5（在状态文本中）。

**Comment by otcbashen** [comment]
非常感谢，太棒了。

**Comment by otcbashen** [comment]
非常感谢，太棒了。

**Comment by otcbashen** [comment]
![Screenshot_20230523_095429](https://github.com/aki65/aki65.github.io/assets/109559896/d35547a2-cb48-4392-b25a-b8f3769fe959)
能否像图片所示显示落子的手数？
