### ISSUE TITLE
What are the net sizes?

### ISSUE THREAD

**Issue by hzyhhzy** [aki65/aki65.github.io#8]
Obviously the "KG 20b" is not a official network, it's much faster and seems much weaker. Is it 20b128f(b20c128)?

**Comment by cryptpark** [comment]
it's a network g170e-b20c256x2-s5303129600-d1228401921.bin.gz. you can check this by unpacking the apk, then unpacking "private.mp3", like a zip. there is a part of the code that completely coincides with the official network

**Comment by cryptpark** [comment]
@hzyhhzy with what parameters did you run? is b20c128 for KG?

**Comment by cryptsport** [comment]
here
https://github.com/lightvector/KataGo/issues/321#issuecomment-739830971
it is written that the network seems to be there. unclear.
@aki65 clarify the question, please. is there a converted network? and if so, only for x64?

**Comment by aki65** [comment]
If you use internal "20b" network, then:
**a)** for 32 bit: network is official g170e-b20c256x2-s5303129600-d1228401921 and it is evaluated as in official KataGo cpu version
**b)** for 64 bit: network is still official g170e-b20c256x2-s5303129600-d1228401921, but it is stored and evaluated in an optimized way. This optimization includes a parallelisation of the evaluation, so it is not very profitable (and may even hurt the results) to parallelize the search too. So you should use numSearchThreads = 1 in config. The optimization may lead to slightly different network results, but this doesn't significantly affect playing strength: I ran a series of test matches at equal playouts between the optimized evaluation and the original one, and the result was even. So the optimized evaluation is certainly not "much weaker".

**Comment by acristescu** [comment]
Can you kindly provide some info on what changes did you make to the 64 bit binary and how to run it now? It seems to want the TensorFlow .so file, but even if that is provided the binary will just exit without an error message. Basically even running `./katago version` crashes like this.

**Comment by aki65** [comment]
I didn't change the way to run it, so I don't have any explanation for you why it behaves as you observe. Without any error messages there is also no clue where to look, so I'm sorry, I can't help you here.
