### ISSUE TITLE
some UI/usability suggestions 

### ISSUE THREAD

**Issue by bltoby** [aki65/aki65.github.io#81]
Cheers for the great app at first.

My suggestions for the UI improvement. See the attached photo please.

Thanks.

![IMG_20230516_134357](https://github.com/aki65/aki65.github.io/assets/129069899/91fdf251-19b7-40b2-be2c-343efa5f0478)

**Comment by aki65** [comment]
Thank you very much for your suggestions. I made a test release that implements them ( https://github.com/aki65/aki65.github.io/releases/tag/v1.18.5 ). It's fully functional, it just hasn't gone through all the testing required for a release. So please try it and check if it suits your needs.

**Comment by bltoby** [comment]
Wow, lightning fast updated 👍

IMHO the 'toggle' button for visibility of analysis is better to be placeed under the original narrow 'own' button. Because we don't need to move the finger up and down frequently to click the distantly placed 'ponder' button and 'toggle' button. 

When possible it will be even better if the circles (suggested mores) be added in a different layer other than the game board layer, so that when pondering the toggling is meantime possible.

**Comment by aki65** [comment]
I implemented your second suggestion here: https://github.com/aki65/aki65.github.io/releases/tag/v1.18.6

**Comment by cryptsport** [comment]
there are not enough clock readings, the time spent on the move and the game

**Comment by cryptsport** [comment]
and how soon can we expect the 32-bit version?

**Comment by aki65** [comment]
I added a 32bit version to release 1.18.7.

Be aware that .dlc files can't be loaded with the 32bit version (Qualcomm doesn't support that).
