### ISSUE TITLE
落子能否在棋盘上显示手数？具体见图。

### ISSUE THREAD

**Issue by otcbashen** [aki65/aki65.github.io#83]
![Screenshot_20230523_095429](https://github.com/aki65/aki65.github.io/assets/109559896/eea65c87-eb0e-4f0c-9ed3-bdd1044e76e5)

落子能否在棋盘上显示手数？具体见图。

**Comment by aki65** [comment]
我不明白这有什么意义：

如果你想看一个位置是如何产生的，通过游戏的步骤（通过点击直方图或 < 和 > 按钮）要容易得多。
如果你想生成一个你的游戏的棋谱，你可以保存sgf，然后把它加载到sgf编辑器（如 cgoban），它可以做到这一点。

此外：
数字在手机上会小得难以辨认（记住它们也可以有3个数字）。
数字会与变体显示的编号相冲突。

**Comment by otcbashen** [comment]
首先感谢您的每次认真的回复。
         不好意思，之前有事不在线。我只是初学者，一开始是用的badukai来区域AI计算解死活题，这点太棒了，手机上也只有badukai能实现了，甚至后来badukai可以棋盘任意放大缩小（针对这点可否增加个按钮一键恢复至初始，一会儿我单开个问题）。
         后续慢慢开始用badukai复盘，这时慢慢开始接触了一些手机上的其他围棋软件如：围棋宝典、阿Q围棋极速版等，对比其他软件的一些功能（围棋宝典没有本地AI复盘、有放大棋盘但不是随意、有数字全盘标记手数；阿Q围棋极速版有本地AI复盘、没有放大棋盘功能、有数字全盘标记手数），就希望badukai的功能越来越强大。
       回到问题本身，这个需求主要是在复盘时能比较清楚的显示手数及落子过程，尤其是对照实际棋盘复盘，不容易出错。上面图片截图来自围棋宝典，下面附一个阿Q围棋极速版的截图参考。
![Uploading IMG_20230609_133735.jpg…]()
        再次感谢，祝愿badukai越来越棒，祝万事如意。

**Comment by otcbashen** [comment]
首先感谢您的每次认真的回复。
         不好意思，之前有事不在线。我只是初学者，一开始是用的badukai来区域AI计算解死活题，这点太棒了，手机上也只有badukai能实现了，甚至后来badukai可以棋盘任意放大缩小（针对这点可否增加个按钮一键恢复至初始，一会儿我单开个问题）。
         后续慢慢开始用badukai复盘，这时慢慢开始接触了一些手机上的其他围棋软件如：围棋宝典、阿Q围棋极速版等，对比其他软件的一些功能（围棋宝典没有本地AI复盘、有放大棋盘但不是随意、有数字全盘标记手数；阿Q围棋极速版有本地AI复盘、没有放大棋盘功能、有数字全盘标记手数），就希望badukai的功能越来越强大。
       回到问题本身，这个需求主要是在复盘时能比较清楚的显示手数及落子过程，尤其是对照实际棋盘复盘，不容易出错。上面图片截图来自围棋宝典，下面附一个阿Q围棋极速版的截图。

        再次感谢，祝愿badukai越来越棒，祝万事如意。

**Comment by otcbashen** [comment]
首先感谢您的每次认真的回复。
         不好意思，之前有事不在线。我只是初学者，一开始是用的badukai来区域AI计算解死活题，这点太棒了，手机上也只有badukai能实现了，甚至后来badukai可以棋盘任意放大缩小（针对这点可否增加个按钮一键恢复至初始，一会儿我单开个问题）。
         后续慢慢开始用badukai复盘，这时慢慢开始接触了一些手机上的其他围棋软件如：围棋宝典、阿Q围棋极速版等，对比其他软件的一些功能（围棋宝典没有本地AI复盘、有放大棋盘但不是随意、有数字全盘标记手数；阿Q围棋极速版有本地AI复盘、没有放大棋盘功能、有数字全盘标记手数），就希望badukai的功能越来越强大。
       回到问题本身，这个需求主要是在复盘时能比较清楚的显示手数及落子过程，尤其是对照实际棋盘复盘，不容易出错。上面图片截图来自围棋宝典，类似功能阿Q围棋极速版也有，截图总是传不上。
        再次感谢，祝愿badukai越来越棒，祝万事如意。

**Comment by otcbashen** [comment]
![IMG_20230609_134755](https://github.com/aki65/aki65.github.io/assets/109559896/5b2482ff-c08d-4bf0-95b9-a85d87ce20f3)
上传图片成功，这是阿Q围棋极速版的截图。

**Comment by aki65** [comment]
数字现在包括在最新的测试版本中：https://github.com/aki65/aki65.github.io/releases/tag/v1.18.8
它们在默认情况下是关闭的，你必须在设置中把它们打开。

**Comment by otcbashen** [comment]
威武，完美实现功能，非常感谢。
