### ISSUE TITLE
哈哈

### ISSUE THREAD

**Issue by ugvvff** [aki65/aki65.github.io#84]
作者有算过fp16量化为高通能用的int8，elo下降了多少吗？对了，您什么时候有空将katago的乐观策略也就是现在最新版的katago更新到手机上？

**Comment by aki65** [comment]
根据我的测试比赛，我可以对量化造成的演奏实力损失做出如下粗略估计 :

老的 (40b/60b): 40 ELO

新的 (18b): 75 ELO

1.13即将到来

**Comment by aki65** [comment]
1.13版在这里 : https://github.com/aki65/aki65.github.io/releases/tag/v1.18.7

**Comment by ugvvff** [comment]
> 

好的，谢谢

**Comment by ugvvff** [comment]
但是我好像并没有在badukai上找到能够调乐观策略的参数？照理说他应该能调，至少pc是是这样

**Comment by aki65** [comment]
KataGo有大约170个参数。我不可能让它们在小的手机屏幕上都能看到。所以我只显示那些 "最佳 "设置取决于使用场景或设备的参数。

但是 "rootPolicyOptimism "和 "policyOptimism "不属于这个类别。已经进行了大量的测试，哪些值能提供最佳的游戏强度，rootPolicyOptimism = 0.2, policyOptimism = 1.0已经被确定为最佳设置。因此，它们已成为1.13.2的默认值，BadukAI使用这些值。
