### ISSUE TITLE
Please help me. Thank you

### ISSUE THREAD

**Issue by Fly143** [aki65/aki65.github.io#85]
When I tried to use lizzieyzy on the computer using adb to connect to the phone and run katago on the phone so that it shows up above lizzieyzy. I succeeded, but only half. It worked and showed up, but it was very slow and not as fast as in the badukai app. How can I solve this problem, make it faster. Please help me, thank you.

**Comment by Fly143** [comment]
The run command I use is: adb/adb.exe shell "cd /data/app/~~djzeideDs0K5dEs2axeV6g==/net.kir.baduk_ai-A8nxhaLX53PYAXdjuHI-AQ==/lib/arm64 && export  LD_LIBRARY_PATH=./:$LD_LIBRARY_PATH && ./libkatago.so gtp -model /data/app/~~djzeideDs0K5dEs2axeV6g==/net.kir.baduk_ai-A8nxhaLX53PYAXdjuHI-AQ==/lib/arm64/b18c384nbt-20230419-optimistic. bin.gz -config /data/app/~~djzeideDs0K5dEs2axeV6g==/net.kir.baduk_ai-A8nxhaLX53PYAXdjuHI-AQ==/lib/arm64/default_gtp.cfg"

**Comment by Fly143** [comment]
Since my computer is not good at running katago, not as good as badukai, I want to run katago on my phone and output the results on my computer

**Comment by aki65** [comment]
I'm sorry, I can't help you with the adb problem.

But perhaps you could try a different approach: Nowadays most phones offer the possibility to display an app on the computer screen and control it by keyboard and mouse (it's called desktop mode or similar depending on manufacturer). That way katago would run within BadukAI, so it should have the usual speed ...
