### ISSUE TITLE
能否增加按钮，一键恢复至默认全屏棋盘状态？

### ISSUE THREAD

**Issue by otcbashen** [aki65/aki65.github.io#86]
badukai可以棋盘任意放大缩小，可否增加一个按钮，按下后一键恢复至默认全屏棋盘状态，放大缩小过程不流畅、反应特别慢。

**Comment by aki65** [comment]
在最新的测试版本中，缩放更加顺畅：https://github.com/aki65/aki65.github.io/releases/tag/v1.18.8
因此不需要额外的按钮： 只要放大到棋盘变得比原来小，然后它就会恢复原来的大小和位置。

**Comment by otcbashen** [comment]
大赞，缩放非常流畅，再次感谢。
