### ISSUE TITLE
启动app时，棋盘有时会显示不完整，上方被遮挡

### ISSUE THREAD

**Issue by zsmhub** [aki65/aki65.github.io#88]
# baduk ai app 反馈

启动app时，棋盘有时会显示不完整，比如19路棋盘只显示了18.5路棋盘，
临时解决方案：先改为9路棋盘再改为19路棋盘界面就能恢复正常，出现该问题的频率挺高的，希望能优化下

app版本：baduk_ai__arm64-v8a-rel-1.19.apk

出现问题的手机型号：三星s23，红米k40 pro（手机系统基本是最新的）

![WechatIMG41](https://github.com/aki65/aki65.github.io/assets/16890747/20367a4e-3a1c-40ec-ab0f-b23bf02d7fbd)

**Comment by aki65** [comment]
这是我使用的UI框架的一个错误。所以我无法修复它，只能尝试绕过它。我在最新的测试版本中这样做了：https://github.com/aki65/aki65.github.io/releases/tag/v1.18.8 
到现在为止，这个问题在我的手机上从未发生过，而且是在那个版本。这不能保证问题真的得到解决，但值得一试。

**Comment by zsmhub** [comment]
> 这是我使用的UI框架的一个错误。所以我无法修复它，只能尝试绕过它。我在最新的测试版本中这样做了：https://github.com/aki65/aki65.github.io/releases/tag/v1.18.8 到现在为止，这个问题在我的手机上从未发生过，而且是在那个版本。这不能保证问题真的得到解决，但值得一试。

好的，我安装试试

**Comment by zsmhub** [comment]
该版本用了几天，没有发现UI异常问题
