### ISSUE TITLE
UI Feedback/improvement

### ISSUE THREAD

**Issue by bltoby** [aki65/aki65.github.io#90]
Could you please move 'undo' button to the left of '<' button. Because if I hold my cellphone with right hand, when trying to tap other buttons, I offen touch the 'undo' button by mistake. It sometimes cause loss of following moves in an unsaved sgf. Thanks.

**Comment by aki65** [comment]
I moved it, see https://github.com/aki65/aki65.github.io/releases/tag/v1.18.9
