### ISSUE TITLE
可否增加旋转棋盘的功能

### ISSUE THREAD

**Issue by otcbashen** [aki65/aki65.github.io#91]
可否增加旋转棋盘的功能，90°或者180°旋转，非常感谢。

**Comment by aki65** [comment]
您需要这样做的目的是什么？

**Comment by otcbashen** [comment]
部分第三人棋谱录入视角不同，180°或90°偏差。疯石有180°偏差。

**Comment by aki65** [comment]
我实施了轮换: https://github.com/aki65/aki65.github.io/releases/tag/v1.18.10

旋转时，将两个手指放在木板上，然后转动你的手。一开始，什么也不会发生，但当旋转角度接近 90° 时，木板就会转过来。

**Comment by otcbashen** [comment]
非常感谢，去试一下。

**Comment by otcbashen** [comment]
太厉害了，再次感谢，解决大问题了。
