### ISSUE TITLE
增加立即悔棋功能和分析每步自定义时间功能

### ISSUE THREAD

**Issue by chaoclc** [aki65/aki65.github.io#95]
1：有时候点错位置以及其它情况需要立即悔棋，需等到baduk_ai思考完成才能悔棋，增加立即悔棋功能会更加方便。
2:增加分析每步自定义时间功能，比如每一手5秒自动停止分析等人选择下一手棋后再自动分析5秒这样连续进行，减少长时间分析引起发热。

**Comment by chaoclc** [comment]
1:可不可以把现在的悔棋按钮改成立即悔棋功能？

2：全部分析按钮增加人下一手棋后再自动设定的时间全部分析，这样可以连续性按照设定的时间分析，现在是分析一次后需要再次点击全部分析按钮，显得很频繁。我的意思是可不可以把全部分析改成点击一次可以连续按设定的时间分析，人下一手棋自动分析5秒，再下一手棋再自动分析5秒这样连续进行。不需要频繁点击全部分析按钮，当需要退出全部分析时只需要点击一下全部分析。

**Comment by chaoclc** [comment]
非常感谢提供怎么好的软件，我自己调整一下使用方法。因此，可以不用修改软件。再次感谢

**Comment by HackYardo** [comment]
我的塑料汉语不足以理解你的那个大段落，如果已经“解决了”请关闭该问题（close this issue）。

**Comment by aki65** [comment]
我在最新测试版本的“时间设置”对话框中添加了用于配置分析移动之间暂停的选项：
https://github.com/aki65/aki65.github.io/releases/tag/v1.18.12

**Comment by aki65** [comment]
1. 一旦 KataGo 开始思考下一步，在思考时间结束之前就不可能阻止他。因此，BadukAI 不允许在此阶段进行任何操作，因为它们无论如何都无法传输到 KataGo。恐怕，没有办法改变这一点。

**Comment by chaoclc** [comment]
我的意思是像KaTrain 只选择最佳选点那样的功能，让人选择BadukAI 分析后的最佳选点，按照设定后的时间并且有此时间规则的每手棋分析，不需要经常点击全部分析按钮。
![Uploading KaTrain.jpg…]()

**Comment by chaoclc** [comment]
![KaTrain](https://github.com/aki65/aki65.github.io/assets/142547080/247eeb91-dd60-4de7-a48b-16b4ee3ee2bf)

**Comment by aki65** [comment]
好的，很抱歉造成了误解。我将调查是否能实现类似功能。

**Comment by chaoclc** [comment]
现在的BadukAI 按钮的中文字，“全部分析”好像更适合用“定时分析”这个中文词。只可惜不能连续定时。

**Comment by chaoclc** [comment]
![baduk_ai](https://github.com/aki65/aki65.github.io/assets/142547080/41929157-810d-49df-b760-9b7c02deec62)

**Comment by chaoclc** [comment]
明白了，现在的BadukAI “全部分析”主要指的是对棋谱的完整分析。KaTrain 的最佳选点可以对棋谱的完整分析，也可以自动连续对接下来的一手棋进行定时分析。

**Comment by aki65** [comment]
在最新的测试版本中 https://github.com/aki65/aki65.github.io/releases/tag/v1.18.13 我在第二个分析按钮上添加了一个计时选项 叫 "现状分析" (时间设置对话框中的第三个设置). 因此，如果您在这里设置了 5 秒钟，然后点击 "现状分析"，BadukAI 就会分析 5 秒钟，然后暂停。但当您改变位置时（通过输入棋步或在 sgf 中导航），它又会继续分析 5 秒钟，以此类推。希望这能满足您的需求 .

**Comment by chaoclc** [comment]
很好，谢谢。管理时间设置  - 分析当前情况的时限制（秒}输入5 ，保存设置。回到界面点击选择“现状分析”就可以设置成自动连续下一手定时5秒分析了。
