### ISSUE TITLE
设定等级后，虚手无法点击。

### ISSUE THREAD

**Issue by otcbashen** [aki65/aki65.github.io#96]
设定等级后，虚手无法点击使用，手头版本是1.8.11、1.8.10，均存在这种情况。

**Comment by aki65** [comment]
我无法重现这种情况。您能否上传一段视频，说明您是如何遇到这种情况的？

**Comment by otcbashen** [comment]
等级设定那里，不填数字，虚手可以使用；等级设定那里，填了数字，虚手无法使用，无法点击。
试过了手机、pad、虚拟机，都是一样的情况。

**Comment by otcbashen** [comment]
录好了，怎么传视频？操作了半天只能选择图片。

**Comment by otcbashen** [comment]
![虚手录像1](https://github.com/aki65/aki65.github.io/assets/109559896/a097630a-f43d-4c2e-bd6b-db38e749e2e5)
录像

**Comment by aki65** [comment]
非常感谢您的视频。您是否在数字“6”后按了“Enter”键？如果没有，请尝试，如果这会改变什么。

**Comment by otcbashen** [comment]
已按您的说法尝试在“等级”设定处输入数字后按“确认”，这并未改变上述结果，虚手还是无法操作。经过尝试，只要输入数字（不按“确认”），在继续游戏，设置就已经生效，其他可以输入数字的设置都做了尝试。

**Comment by otcbashen** [comment]
刚才又做了测试，用的最新的1.8.12版本，发现只要在等级设置那里输入数字，顶部“虚手”就变暗（无法操作），等级设置那里删除数字，顶部“虚手”就变亮（可以操作），具体录像见上。感谢您的认真回复。

**Comment by aki65** [comment]
这是故意的： 当您进入一个关卡时，您的对手不是 KataGo（因为它太强大了），而是一个非常简单的机器人。尤其是，这个机器人无法估算分数。因此，它无法辞职。因此，无论如何您都必须手动结束对局。因此，弃权毫无用处，因此该按钮被禁用。

**Comment by otcbashen** [comment]
明白了，感谢答复。
