### ISSUE TITLE
最后一手的显示颜色可否改为红色？

### ISSUE THREAD

**Issue by otcbashen** [aki65/aki65.github.io#97]
最后一手的显示颜色可否改为红色？现在显示的灰色，棋盘棋子很多时，找到最后一手比较费劲。

**Comment by HackYardo** [comment]
真实比赛时对手不会告诉你他或她下哪里了为此马晓春在世界大赛上连走两步直接判负了。

**Comment by otcbashen** [comment]
手机屏幕较小，红色比较醒目，可以参考疯石、阿Q围棋，围棋宝典等软件，谢谢。

**Comment by aki65** [comment]
我在最新的测试版本中更改了颜色: https://github.com/aki65/aki65.github.io/releases/tag/v1.18.12

**Comment by otcbashen** [comment]
感谢您的更新，软件越来越棒。
