### ISSUE TITLE
加载sgf后无法添加、移除棋子

### ISSUE THREAD

**Issue by otcbashen** [aki65/aki65.github.io#98]
加载sgf后无法添加、移除棋子，无法对sgf进行修正。

**Comment by HackYardo** [comment]
需要上传sgf文件看看问题在哪。

**Comment by otcbashen** [comment]
我没描述清楚问题，所有的sgf加载后，都无法再进行添加、移除棋子的操作，不能编辑。

**Comment by otcbashen** [comment]
试验了下，软件的逻辑是加载空棋盘后可以添加、移除棋子，交替落子后，无法再进行添加、移除棋子的操作。保存为sgf后，再重新加载该sgf，也无法再进行添加、移除棋子的操作。所有交替落子行棋的sgf均存在这种问题。

**Comment by aki65** [comment]
这是故意的：一旦有了移动序列，您就无法再编辑位置，因为这可能会产生冲突。

如果你想编辑加载的 sgf 的结束位置作为新内容的起点，你必须首先使用以下“技巧”摆脱移动序列：
进行额外的移动（以触发自动保存机制），然后在 sgf 对话框中点击“加载上一盘面”。然后BadukAI 将加载棋盘位置，而无需任何移动导致该位置。所以你可以编辑它。

**Comment by otcbashen** [comment]
感谢您的细心答复，按您的操作可以解决问题，再次感谢，软件越来越棒。
